/// Reusable widgets and utilities for the visual keymap editor.
///
/// Contains data models, script generation, and widget components
/// used by EditorPage.
library;

import 'package:flutter/material.dart';

import '../ffi/bridge.dart';
import '../widgets/layer_panel.dart';

/// Types of key actions available in the editor.
enum KeyActionType { remap, block, pass }

extension KeyActionTypeLabel on KeyActionType {
  String get label {
    switch (this) {
      case KeyActionType.remap:
        return 'Remap';
      case KeyActionType.block:
        return 'Block';
      case KeyActionType.pass:
        return 'Pass through';
    }
  }
}

/// Represents a single key mapping configuration.
class KeyMapping {
  const KeyMapping({
    required this.from,
    required this.type,
    this.to,
    this.layer,
    this.tapHoldTap,
    this.tapHoldHold,
  });

  final String from;
  final KeyActionType type;
  final String? to;
  final String? layer;
  final String? tapHoldTap;
  final String? tapHoldHold;
}

/// Represents a combo (multiple keys pressed together) configuration.
class ComboMapping {
  const ComboMapping({required this.keys, required this.output});

  final List<String> keys;
  final String output;
}

/// Utility for building Rhai scripts from mappings and combos.
class ScriptGenerator {
  static String build({
    required Iterable<KeyMapping> mappings,
    required Iterable<ComboMapping> combos,
  }) {
    final buffer = StringBuffer()
      ..writeln('// Auto-generated by KeyRx Editor')
      ..writeln('// Edit carefully or re-generate from the UI.')
      ..writeln()
      ..writeln('fn configure() {');

    for (final mapping in mappings) {
      switch (mapping.type) {
        case KeyActionType.remap:
          buffer.writeln(
            '    remap("${mapping.from}", "${mapping.to ?? mapping.from}");',
          );
          break;
        case KeyActionType.block:
          buffer.writeln('    block("${mapping.from}");');
          break;
        case KeyActionType.pass:
          buffer.writeln('    pass("${mapping.from}");');
          break;
      }

      if (mapping.layer != null && mapping.layer!.isNotEmpty) {
        buffer.writeln(
          '    layer("${mapping.layer}", "${mapping.from}", "${mapping.to ?? mapping.from}");',
        );
      }

      if (mapping.tapHoldTap != null &&
          mapping.tapHoldHold != null &&
          mapping.tapHoldTap!.isNotEmpty &&
          mapping.tapHoldHold!.isNotEmpty) {
        buffer.writeln(
          '    tap_hold("${mapping.from}", tap: "${mapping.tapHoldTap}", hold: "${mapping.tapHoldHold}");',
        );
      }
    }

    if (combos.isNotEmpty) {
      buffer.writeln();
      buffer.writeln('    // Combos');
      for (final combo in combos) {
        final keys = combo.keys.map((k) => '"$k"').join(', ');
        buffer.writeln('    combo([$keys], "${combo.output}");');
      }
    }

    buffer.writeln('}');
    return buffer.toString();
  }
}

/// Utility functions and constants for key validation.
class KeyMappings {
  static List<String> allowedKeys = [
    'esc', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11',
    'f12', '`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=',
    'backspace', 'tab', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[',
    ']', '\\', 'capslock', 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';',
    "'", 'enter', 'lshift', 'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/',
    'rshift', 'lctrl', 'lwin', 'lalt', 'space', 'ralt', 'rwin', 'menu', 'rctrl',
  ];

  static bool isKnownKey(String key) {
    if (key.isEmpty) return false;
    final normalized = key.toLowerCase();
    return allowedKeys.contains(normalized);
  }

  /// Allow runtime updates from the native bridge.
  static void updateAllowedKeys(List<String> keys) {
    if (keys.isNotEmpty) {
      final normalized =
          keys
              .map((k) => k.toLowerCase())
              .where((k) => k.isNotEmpty)
              .toSet()
              .toList()
            ..sort();
      allowedKeys = normalized;
    }
  }
}

/// Widget for displaying and configuring a single key mapping.
class KeyConfigPanel extends StatelessWidget {
  const KeyConfigPanel({
    super.key, required this.selectedKey, required this.selectedAction,
    required this.outputController, required this.layerController,
    required this.tapOutputController, required this.holdOutputController,
    required this.onActionChanged, required this.onApply,
  });

  final String? selectedKey;
  final KeyActionType selectedAction;
  final TextEditingController outputController;
  final TextEditingController layerController;
  final TextEditingController tapOutputController;
  final TextEditingController holdOutputController;
  final ValueChanged<KeyActionType?> onActionChanged;
  final VoidCallback onApply;

  @override
  Widget build(BuildContext context) {
    if (selectedKey == null) {
      return const Center(child: Text('Select a key to configure'));
    }
    final isRemap = selectedAction == KeyActionType.remap;
    return Padding(
      padding: const EdgeInsets.all(16),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Text('Configuring: $selectedKey',
            style: Theme.of(context).textTheme.titleLarge),
        if (!KeyMappings.isKnownKey(selectedKey!)) ...[
          const SizedBox(height: 4),
          Text('$selectedKey is not in the canonical key list.',
              style: TextStyle(color: Colors.orange.shade700)),
        ],
        const SizedBox(height: 16),
        Row(children: [
          DropdownButton<KeyActionType>(
            value: selectedAction,
            items: KeyActionType.values
                .map((t) => DropdownMenuItem(value: t, child: Text(t.label)))
                .toList(),
            onChanged: onActionChanged,
          ),
          const SizedBox(width: 16),
          Expanded(
            child: TextField(
              controller: outputController,
              decoration: InputDecoration(
                labelText: isRemap ? 'Remap to key' : 'Optional note',
                hintText: isRemap ? 'e.g., Escape' : 'Leave blank for block/pass',
              ),
              enabled: isRemap,
            ),
          ),
          const SizedBox(width: 12),
          FilledButton.icon(
              icon: const Icon(Icons.check), label: const Text('Apply'),
              onPressed: onApply),
        ]),
        const SizedBox(height: 12),
        Row(children: [
          Expanded(child: TextField(controller: layerController,
              decoration: const InputDecoration(
                  labelText: 'Layer (optional)', hintText: 'e.g., navigation'))),
          const SizedBox(width: 12),
          Expanded(child: TextField(controller: tapOutputController,
              decoration: const InputDecoration(
                  labelText: 'Tap output (tap-hold)', hintText: 'e.g., Escape'))),
          const SizedBox(width: 12),
          Expanded(child: TextField(controller: holdOutputController,
              decoration: const InputDecoration(
                  labelText: 'Hold output (tap-hold)', hintText: 'e.g., Ctrl'))),
        ]),
      ]),
    );
  }
}

/// Widget for displaying the combo configuration row.
class ComboConfigRow extends StatelessWidget {
  const ComboConfigRow({
    super.key, required this.comboKeysController, required this.comboOutputController,
    required this.combos, required this.onAddCombo, required this.onRemoveCombo,
  });

  final TextEditingController comboKeysController;
  final TextEditingController comboOutputController;
  final List<ComboMapping> combos;
  final VoidCallback onAddCombo;
  final ValueChanged<int> onRemoveCombo;

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Text('Combos', style: Theme.of(context).textTheme.titleMedium),
          const SizedBox(height: 8),
          Row(children: [
            Expanded(child: TextField(controller: comboKeysController,
                decoration: const InputDecoration(
                    labelText: 'Keys (comma-separated)', hintText: 'e.g., A,S'))),
            const SizedBox(width: 12),
            Expanded(child: TextField(controller: comboOutputController,
                decoration: const InputDecoration(
                    labelText: 'Output', hintText: 'e.g., Ctrl'))),
            const SizedBox(width: 12),
            FilledButton.icon(onPressed: onAddCombo, icon: const Icon(Icons.add),
                label: const Text('Add Combo')),
          ]),
          const SizedBox(height: 8),
          if (combos.isEmpty) const Text('No combos defined.')
          else ...combos.asMap().entries.map((e) => ListTile(
            dense: true, leading: const Icon(Icons.merge_type),
            title: Text('${e.value.keys.join(" + ")} → ${e.value.output}'),
            trailing: IconButton(icon: const Icon(Icons.delete),
                onPressed: () => onRemoveCombo(e.key)),
          )),
        ]),
      ),
    );
  }
}

/// Widget for displaying the list of key mappings with a layer panel.
class MappingListPanel extends StatelessWidget {
  const MappingListPanel({
    super.key, required this.mappings, required this.layers,
    required this.onRemoveMapping, required this.onAddLayer,
    required this.onToggleLayer,
  });

  final Map<String, KeyMapping> mappings;
  final List<LayerInfo> layers;
  final ValueChanged<String> onRemoveMapping;
  final VoidCallback onAddLayer;
  final void Function(String name, bool active) onToggleLayer;

  @override
  Widget build(BuildContext context) {
    if (mappings.isEmpty) {
      return const Center(child: Text('No mappings yet. Add one to continue.'));
    }
    return Row(children: [
      Expanded(flex: 2, child: ListView(
        children: mappings.values.map((m) => ListTile(
          leading: const Icon(Icons.keyboard),
          title: Text('${m.from} → ${_describeMapping(m)}'),
          subtitle: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text(_describeDetails(m)),
            const SizedBox(height: 4),
            Wrap(spacing: 6, runSpacing: 4, children: [
              KeyValidityChip(label: 'from ${m.from}',
                  isValid: KeyMappings.isKnownKey(m.from)),
              if (m.to != null && m.to!.isNotEmpty)
                KeyValidityChip(label: 'to ${m.to}',
                    isValid: KeyMappings.isKnownKey(m.to!)),
            ]),
          ]),
          trailing: IconButton(icon: const Icon(Icons.delete),
              onPressed: () => onRemoveMapping(m.from)),
        )).toList(),
      )),
      const SizedBox(width: 12),
      Expanded(flex: 1, child: LayerPanel(
          layers: layers, onAddLayer: onAddLayer, onToggleLayer: onToggleLayer)),
    ]);
  }

  String _describeMapping(KeyMapping m) => switch (m.type) {
    KeyActionType.remap => m.to ?? '',
    KeyActionType.block => 'blocked',
    KeyActionType.pass => 'pass through',
  };

  String _describeDetails(KeyMapping m) {
    final parts = <String>[];
    if (m.layer != null && m.layer!.isNotEmpty) parts.add('Layer: ${m.layer}');
    if (m.tapHoldTap?.isNotEmpty == true && m.tapHoldHold?.isNotEmpty == true) {
      parts.add('Tap/Hold: ${m.tapHoldTap} / ${m.tapHoldHold}');
    }
    return parts.isEmpty ? m.type.label : parts.join(' • ');
  }
}

/// Widget for displaying the key registry status banner.
class KeyRegistryBanner extends StatelessWidget {
  const KeyRegistryBanner({
    super.key, required this.isFetchingKeys, required this.usingFallbackKeys,
    required this.canonicalKeysCount, required this.registryError,
    required this.onRefresh,
  });

  final bool isFetchingKeys;
  final bool usingFallbackKeys;
  final int canonicalKeysCount;
  final String? registryError;
  final VoidCallback onRefresh;

  @override
  Widget build(BuildContext context) {
    final statusText = isFetchingKeys ? 'Fetching canonical keys...'
        : usingFallbackKeys ? 'Using fallback key list'
        : 'Loaded $canonicalKeysCount canonical keys';
    final color = usingFallbackKeys ? Colors.orange : Colors.green;
    return Card(
      margin: EdgeInsets.zero, elevation: 0,
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        child: Row(children: [
          Icon(Icons.key, color: color),
          const SizedBox(width: 8),
          Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(statusText,
                  style: TextStyle(color: color, fontWeight: FontWeight.w600)),
              if (registryError != null)
                Text(registryError!, style: TextStyle(color: Colors.orange.shade700),
                    overflow: TextOverflow.ellipsis),
            ],
          )),
          if (isFetchingKeys)
            const SizedBox(width: 16, height: 16,
                child: CircularProgressIndicator(strokeWidth: 2))
          else
            IconButton(icon: const Icon(Icons.refresh),
                tooltip: 'Refresh key registry', onPressed: onRefresh),
        ]),
      ),
    );
  }
}

/// Chip widget for displaying key validity status.
class KeyValidityChip extends StatelessWidget {
  const KeyValidityChip({super.key, required this.label, required this.isValid});

  final String label;
  final bool isValid;

  @override
  Widget build(BuildContext context) {
    final baseColor = isValid ? Colors.green : Colors.redAccent;
    return Chip(
      label: Text(label),
      backgroundColor: baseColor.withValues(alpha: 0.12),
      labelStyle: TextStyle(color: baseColor, fontWeight: FontWeight.w600),
      visualDensity: VisualDensity.compact,
      side: BorderSide(color: baseColor.withValues(alpha: 0.5)),
    );
  }
}

/// Widget for displaying script validation status banner.
class ValidationBanner extends StatelessWidget {
  const ValidationBanner({
    super.key,
    required this.isValidating,
    required this.validationResult,
    required this.onShowErrors,
  });

  final bool isValidating;
  final ScriptValidationResult? validationResult;
  final void Function(List<ScriptValidationError> errors) onShowErrors;

  @override
  Widget build(BuildContext context) {
    if (isValidating) {
      return Container(
        color: Colors.blue.withValues(alpha: 0.1),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        child: const Row(
          children: [
            SizedBox(
              width: 16,
              height: 16,
              child: CircularProgressIndicator(strokeWidth: 2),
            ),
            SizedBox(width: 8),
            Text('Validating script...'),
          ],
        ),
      );
    }

    final result = validationResult;
    if (result == null || result.valid) {
      return const SizedBox.shrink();
    }

    final errors = result.errors;
    final errorMessage = result.errorMessage;

    return Material(
      color: Colors.red.withValues(alpha: 0.15),
      child: InkWell(
        onTap: errors.isNotEmpty ? () => onShowErrors(errors) : null,
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
          child: Row(
            children: [
              const Icon(Icons.error_outline, color: Colors.red, size: 20),
              const SizedBox(width: 8),
              Expanded(
                child: Text(
                  errorMessage ??
                      (errors.isNotEmpty
                          ? 'Script has ${errors.length} error${errors.length > 1 ? 's' : ''}: ${errors.first.message}'
                          : 'Script validation failed'),
                  style: const TextStyle(color: Colors.red),
                  overflow: TextOverflow.ellipsis,
                ),
              ),
              if (errors.isNotEmpty) ...[
                const SizedBox(width: 8),
                const Icon(Icons.chevron_right, color: Colors.red),
              ],
            ],
          ),
        ),
      ),
    );
  }
}

/// Shows a dialog with validation errors.
void showValidationErrorsDialog(BuildContext context, List<ScriptValidationError> errors) {
  showDialog(
    context: context,
    builder: (ctx) => AlertDialog(
      title: const Text('Script Validation Errors'),
      content: SizedBox(
        width: double.maxFinite,
        child: ListView.separated(
          shrinkWrap: true,
          itemCount: errors.length,
          separatorBuilder: (_, __) => const Divider(),
          itemBuilder: (_, index) {
            final e = errors[index];
            return ListTile(
              leading: const Icon(Icons.error, color: Colors.red),
              title: Text(e.message),
              subtitle: e.line != null
                  ? Text('Line ${e.line}${e.column != null ? ', Column ${e.column}' : ''}')
                  : null,
              dense: true,
            );
          },
        ),
      ),
      actions: [TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('Close'))],
    ),
  );
}
