/// Visual keymap editor page.
///
/// Provides a drag-and-drop interface for creating key mappings
/// that generates the underlying Rhai script automatically.

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../services/engine_service.dart';
import '../services/service_registry.dart';
import '../widgets/keyboard.dart';
import '../widgets/layer_panel.dart';

enum KeyActionType { remap, block, pass }

extension on KeyActionType {
  String get label {
    switch (this) {
      case KeyActionType.remap:
        return 'Remap';
      case KeyActionType.block:
        return 'Block';
      case KeyActionType.pass:
        return 'Pass through';
    }
  }
}

class KeyMapping {
  const KeyMapping({
    required this.from,
    required this.type,
    this.to,
    this.layer,
    this.tapHoldTap,
    this.tapHoldHold,
  });

  final String from;
  final KeyActionType type;
  final String? to;
  final String? layer;
  final String? tapHoldTap;
  final String? tapHoldHold;
}

class ComboMapping {
  const ComboMapping({required this.keys, required this.output});

  final List<String> keys;
  final String output;
}

/// Utility for building Rhai scripts from mappings and combos.
class ScriptGenerator {
  static String build({
    required Iterable<KeyMapping> mappings,
    required Iterable<ComboMapping> combos,
  }) {
    final buffer = StringBuffer()
      ..writeln('// Auto-generated by KeyRx Editor')
      ..writeln('// Edit carefully or re-generate from the UI.')
      ..writeln()
      ..writeln('fn configure() {');

    for (final mapping in mappings) {
      switch (mapping.type) {
        case KeyActionType.remap:
          buffer.writeln(
            '    remap("${mapping.from}", "${mapping.to ?? mapping.from}");',
          );
          break;
        case KeyActionType.block:
          buffer.writeln('    block("${mapping.from}");');
          break;
        case KeyActionType.pass:
          buffer.writeln('    pass("${mapping.from}");');
          break;
      }

      if (mapping.layer != null && mapping.layer!.isNotEmpty) {
        buffer.writeln(
          '    layer("${mapping.layer}", "${mapping.from}", "${mapping.to ?? mapping.from}");',
        );
      }

      if (mapping.tapHoldTap != null &&
          mapping.tapHoldHold != null &&
          mapping.tapHoldTap!.isNotEmpty &&
          mapping.tapHoldHold!.isNotEmpty) {
        buffer.writeln(
          '    tap_hold("${mapping.from}", tap: "${mapping.tapHoldTap}", hold: "${mapping.tapHoldHold}");',
        );
      }
    }

    if (combos.isNotEmpty) {
      buffer.writeln();
      buffer.writeln('    // Combos');
      for (final combo in combos) {
        final keys = combo.keys.map((k) => '"$k"').join(', ');
        buffer.writeln('    combo([$keys], "${combo.output}");');
      }
    }

    buffer.writeln('}');
    return buffer.toString();
  }
}

/// Utility functions and constants for key validation.
class KeyMappings {
  static List<String> allowedKeys = [
    'esc',
    'f1',
    'f2',
    'f3',
    'f4',
    'f5',
    'f6',
    'f7',
    'f8',
    'f9',
    'f10',
    'f11',
    'f12',
    '`',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '0',
    '-',
    '=',
    'backspace',
    'tab',
    'q',
    'w',
    'e',
    'r',
    't',
    'y',
    'u',
    'i',
    'o',
    'p',
    '[',
    ']',
    '\\',
    'capslock',
    'a',
    's',
    'd',
    'f',
    'g',
    'h',
    'j',
    'k',
    'l',
    ';',
    "'",
    'enter',
    'lshift',
    'z',
    'x',
    'c',
    'v',
    'b',
    'n',
    'm',
    ',',
    '.',
    '/',
    'rshift',
    'lctrl',
    'lwin',
    'lalt',
    'space',
    'ralt',
    'rwin',
    'menu',
    'rctrl',
  ];

  static bool isKnownKey(String key) {
    if (key.isEmpty) return false;
    final normalized = key.toLowerCase();
    return allowedKeys.contains(normalized);
  }

  /// Allow runtime updates from the native bridge.
  static void updateAllowedKeys(List<String> keys) {
    if (keys.isNotEmpty) {
      final normalized =
          keys
              .map((k) => k.toLowerCase())
              .where((k) => k.isNotEmpty)
              .toSet()
              .toList()
            ..sort();
      allowedKeys = normalized;
    }
  }
}

/// Visual keymap editor page.
class EditorPage extends StatefulWidget {
  const EditorPage({super.key});

  @override
  State<EditorPage> createState() => _EditorPageState();
}

class _EditorPageState extends State<EditorPage> {
  EngineService? _engine;
  String? _selectedKey;
  KeyActionType _selectedAction = KeyActionType.remap;
  final TextEditingController _outputController = TextEditingController();
  final TextEditingController _layerController = TextEditingController();
  final TextEditingController _tapOutputController = TextEditingController();
  final TextEditingController _holdOutputController = TextEditingController();
  final TextEditingController _comboKeysController = TextEditingController();
  final TextEditingController _comboOutputController = TextEditingController();
  final Map<String, KeyMapping> _mappings = {};
  final List<ComboMapping> _combos = [];
  bool _isSaving = false;
  bool _isFetchingKeys = false;
  bool _usingFallbackKeys = false;
  String? _registryError;
  List<String> _canonicalKeys = KeyMappings.allowedKeys;
  static const String _defaultScriptPath = 'scripts/generated.rhai';
  List<LayerInfo> _layers = const [
    LayerInfo(name: 'base', active: true, priority: 0),
  ];

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final registry = Provider.of<ServiceRegistry>(context, listen: false);
      _engine = registry.engineService;
      _fetchKeyRegistry();
    });
  }

  @override
  void dispose() {
    _outputController.dispose();
    _layerController.dispose();
    _tapOutputController.dispose();
    _holdOutputController.dispose();
    _comboKeysController.dispose();
    _comboOutputController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Keymap Editor'),
        actions: [
          IconButton(
            icon: const Icon(Icons.save),
            onPressed: _isSaving ? null : _saveScript,
            tooltip: 'Save Script',
          ),
          IconButton(
            icon: const Icon(Icons.code),
            onPressed: _viewScript,
            tooltip: 'View Generated Script',
          ),
        ],
      ),
      body: Column(
        children: [
          _buildRegistryBanner(),
          // Keyboard visualization
          Expanded(
            flex: 2,
            child: KeyboardWidget(
              onKeySelected: (key) {
                setState(() {
                  _selectedKey = key;
                  _outputController.text = _mappings[key]?.to ?? '';
                  _layerController.text = _mappings[key]?.layer ?? '';
                  _tapOutputController.text = _mappings[key]?.tapHoldTap ?? '';
                  _holdOutputController.text =
                      _mappings[key]?.tapHoldHold ?? '';
                  _selectedAction = _mappings[key]?.type ?? KeyActionType.remap;
                });
              },
              selectedKey: _selectedKey,
            ),
          ),
          // Key configuration panel
          Expanded(flex: 1, child: _buildConfigPanel()),
        ],
      ),
    );
  }

  Widget _buildConfigPanel() {
    if (_selectedKey == null) {
      return const Center(child: Text('Select a key to configure'));
    }

    return Padding(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Configuring: $_selectedKey',
            style: Theme.of(context).textTheme.titleLarge,
          ),
          if (_selectedKey != null && !_isValidKey(_selectedKey!)) ...[
            const SizedBox(height: 4),
            Text(
              '$_selectedKey is not in the canonical key list.',
              style: TextStyle(color: Colors.orange.shade700),
            ),
          ],
          const SizedBox(height: 16),
          Row(
            children: [
              DropdownButton<KeyActionType>(
                value: _selectedAction,
                items: KeyActionType.values
                    .map(
                      (type) => DropdownMenuItem(
                        value: type,
                        child: Text(type.label),
                      ),
                    )
                    .toList(),
                onChanged: (value) {
                  if (value == null) return;
                  setState(() {
                    _selectedAction = value;
                  });
                },
              ),
              const SizedBox(width: 16),
              Expanded(
                child: TextField(
                  controller: _outputController,
                  decoration: InputDecoration(
                    labelText: _selectedAction == KeyActionType.remap
                        ? 'Remap to key'
                        : 'Optional note',
                    hintText: _selectedAction == KeyActionType.remap
                        ? 'e.g., Escape'
                        : 'Leave blank for block/pass',
                  ),
                  enabled: _selectedAction == KeyActionType.remap,
                ),
              ),
              const SizedBox(width: 12),
              FilledButton.icon(
                icon: const Icon(Icons.check),
                label: const Text('Apply'),
                onPressed: _applyMapping,
              ),
            ],
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              Expanded(
                child: TextField(
                  controller: _layerController,
                  decoration: const InputDecoration(
                    labelText: 'Layer (optional)',
                    hintText: 'e.g., navigation',
                  ),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: TextField(
                  controller: _tapOutputController,
                  decoration: const InputDecoration(
                    labelText: 'Tap output (tap-hold)',
                    hintText: 'e.g., Escape',
                  ),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: TextField(
                  controller: _holdOutputController,
                  decoration: const InputDecoration(
                    labelText: 'Hold output (tap-hold)',
                    hintText: 'e.g., Ctrl',
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          Expanded(child: _buildMappingList()),
          const SizedBox(height: 12),
          _buildComboRow(),
        ],
      ),
    );
  }

  Widget _buildComboRow() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Combos', style: Theme.of(context).textTheme.titleMedium),
            const SizedBox(height: 8),
            Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _comboKeysController,
                    decoration: const InputDecoration(
                      labelText: 'Keys (comma-separated)',
                      hintText: 'e.g., A,S',
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: TextField(
                    controller: _comboOutputController,
                    decoration: const InputDecoration(
                      labelText: 'Output',
                      hintText: 'e.g., Ctrl',
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                FilledButton.icon(
                  onPressed: _addCombo,
                  icon: const Icon(Icons.add),
                  label: const Text('Add Combo'),
                ),
              ],
            ),
            const SizedBox(height: 8),
            if (_combos.isEmpty)
              const Text('No combos defined.')
            else
              ..._combos.asMap().entries.map((entry) {
                final index = entry.key;
                final combo = entry.value;
                return ListTile(
                  dense: true,
                  leading: const Icon(Icons.merge_type),
                  title: Text('${combo.keys.join(" + ")} → ${combo.output}'),
                  trailing: IconButton(
                    icon: const Icon(Icons.delete),
                    onPressed: () => setState(() => _combos.removeAt(index)),
                  ),
                );
              }),
          ],
        ),
      ),
    );
  }

  Widget _buildMappingList() {
    if (_mappings.isEmpty) {
      return const Center(child: Text('No mappings yet. Add one to continue.'));
    }

    return Row(
      children: [
        Expanded(
          flex: 2,
          child: ListView(
            children: _mappings.values
                .map(
                  (m) => ListTile(
                    leading: const Icon(Icons.keyboard),
                    title: Text('${m.from} → ${_describeMapping(m)}'),
                    subtitle: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(_describeDetails(m)),
                        const SizedBox(height: 4),
                        Wrap(
                          spacing: 6,
                          runSpacing: 4,
                          children: [
                            _buildValidityChip(
                              'from ${m.from}',
                              _isValidKey(m.from),
                            ),
                            if (m.to != null && m.to!.isNotEmpty)
                              _buildValidityChip(
                                'to ${m.to}',
                                _isValidKey(m.to!),
                              ),
                          ],
                        ),
                      ],
                    ),
                    trailing: IconButton(
                      icon: const Icon(Icons.delete),
                      onPressed: () => _removeMapping(m.from),
                    ),
                  ),
                )
                .toList(),
          ),
        ),
        const SizedBox(width: 12),
        Expanded(
          flex: 1,
          child: LayerPanel(
            layers: _layers,
            onAddLayer: () {
              setState(() {
                final next = 'layer_${_layers.length}';
                _layers = [
                  ..._layers,
                  LayerInfo(
                    name: next,
                    active: false,
                    priority: _layers.length,
                  ),
                ];
              });
            },
            onToggleLayer: (name, active) {
              setState(() {
                final idx = _layers.indexWhere((l) => l.name == name);
                if (idx >= 0) {
                  _layers = [
                    ..._layers.sublist(0, idx),
                    LayerInfo(
                      name: name,
                      active: active,
                      priority: _layers[idx].priority,
                    ),
                    ..._layers.sublist(idx + 1),
                  ];
                }
              });
            },
          ),
        ),
      ],
    );
  }

  String _describeMapping(KeyMapping mapping) {
    switch (mapping.type) {
      case KeyActionType.remap:
        return mapping.to ?? '';
      case KeyActionType.block:
        return 'blocked';
      case KeyActionType.pass:
        return 'pass through';
    }
  }

  String _describeDetails(KeyMapping mapping) {
    final parts = <String>[];
    if (mapping.layer != null && mapping.layer!.isNotEmpty) {
      parts.add('Layer: ${mapping.layer}');
    }
    if (mapping.tapHoldTap != null &&
        mapping.tapHoldTap!.isNotEmpty &&
        mapping.tapHoldHold != null &&
        mapping.tapHoldHold!.isNotEmpty) {
      parts.add('Tap/Hold: ${mapping.tapHoldTap} / ${mapping.tapHoldHold}');
    }
    return parts.isEmpty ? mapping.type.label : parts.join(' • ');
  }

  void _applyMapping() {
    if (_selectedKey == null) return;
    if (_selectedAction == KeyActionType.remap &&
        _outputController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Provide a target key for remap.')),
      );
      return;
    }

    final fromKey = _selectedKey!;
    if (!KeyMappings.isKnownKey(fromKey)) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Unknown key: $fromKey')));
      return;
    }

    if (_selectedAction == KeyActionType.remap &&
        !KeyMappings.isKnownKey(_outputController.text.trim())) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Unknown target key: ${_outputController.text.trim()}'),
        ),
      );
      return;
    }

    final mapping = KeyMapping(
      from: fromKey,
      type: _selectedAction,
      to: _selectedAction == KeyActionType.remap
          ? _outputController.text.trim()
          : null,
      layer: _layerController.text.trim().isEmpty
          ? null
          : _layerController.text.trim(),
      tapHoldTap: _tapOutputController.text.trim().isEmpty
          ? null
          : _tapOutputController.text.trim(),
      tapHoldHold: _holdOutputController.text.trim().isEmpty
          ? null
          : _holdOutputController.text.trim(),
    );

    setState(() {
      _mappings[_selectedKey!] = mapping;
    });
  }

  Future<void> _saveScript() async {
    if (_mappings.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Add at least one mapping before saving.'),
        ),
      );
      return;
    }

    setState(() => _isSaving = true);
    final script = ScriptGenerator.build(
      mappings: _mappings.values,
      combos: _combos,
    );

    try {
      final file = File(_defaultScriptPath);
      await file.parent.create(recursive: true);
      await file.writeAsString(script);

      // Attempt to load the script into the engine if ready.
      final registry = Provider.of<ServiceRegistry>(context, listen: false);
      final engine = registry.engineService;
      final loaded = engine.isInitialized
          ? await engine.loadScript(_defaultScriptPath)
          : false;

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            loaded
                ? 'Script saved and loaded from $_defaultScriptPath'
                : 'Script saved to $_defaultScriptPath',
          ),
        ),
      );
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Failed to save script: $e')));
    } finally {
      if (mounted) {
        setState(() => _isSaving = false);
      }
    }
  }

  void _viewScript() {
    final script = ScriptGenerator.build(
      mappings: _mappings.values,
      combos: _combos,
    );
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Generated Script'),
        content: SingleChildScrollView(child: SelectableText(script)),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }

  void _removeMapping(String key) {
    setState(() {
      _mappings.remove(key);
      if (_selectedKey == key) {
        _outputController.clear();
      }
    });
  }

  void _addCombo() {
    final keys = _comboKeysController.text
        .split(',')
        .map((k) => k.trim())
        .where((k) => k.isNotEmpty)
        .toList();
    final output = _comboOutputController.text.trim();

    if (keys.length < 2 || output.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Provide at least 2 keys and an output.')),
      );
      return;
    }

    if (keys.any((k) => !_isValidKey(k))) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Unknown key in combo.')));
      return;
    }

    setState(() {
      _combos.add(ComboMapping(keys: keys, output: output));
      _comboKeysController.clear();
      _comboOutputController.clear();
    });
  }

  Future<void> _fetchKeyRegistry() async {
    final engine = _engine;
    if (engine == null) return;

    setState(() {
      _isFetchingKeys = true;
      _registryError = null;
    });

    final result = await engine.fetchKeyRegistry();
    if (!mounted) return;

    final canonical = result.entries
        .expand((entry) => [entry.name, ...entry.aliases])
        .map((k) => k.toLowerCase())
        .where((k) => k.isNotEmpty)
        .toList();
    if (canonical.isNotEmpty) {
      KeyMappings.updateAllowedKeys(canonical);
    }

    setState(() {
      _canonicalKeys = KeyMappings.allowedKeys;
      _usingFallbackKeys = result.usedFallback;
      _registryError = result.error;
      _isFetchingKeys = false;
    });
  }

  Widget _buildRegistryBanner() {
    final statusText = _isFetchingKeys
        ? 'Fetching canonical keys...'
        : _usingFallbackKeys
        ? 'Using fallback key list'
        : 'Loaded ${_canonicalKeys.length} canonical keys';
    final color = _usingFallbackKeys ? Colors.orange : Colors.green;

    return Card(
      margin: EdgeInsets.zero,
      elevation: 0,
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        child: Row(
          children: [
            Icon(Icons.key, color: color),
            const SizedBox(width: 8),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    statusText,
                    style: TextStyle(color: color, fontWeight: FontWeight.w600),
                  ),
                  if (_registryError != null)
                    Text(
                      _registryError!,
                      style: TextStyle(color: Colors.orange.shade700),
                      overflow: TextOverflow.ellipsis,
                    ),
                ],
              ),
            ),
            if (_isFetchingKeys)
              const SizedBox(
                width: 16,
                height: 16,
                child: CircularProgressIndicator(strokeWidth: 2),
              )
            else
              IconButton(
                icon: const Icon(Icons.refresh),
                tooltip: 'Refresh key registry',
                onPressed: _fetchKeyRegistry,
              ),
          ],
        ),
      ),
    );
  }

  Widget _buildValidityChip(String label, bool isValid) {
    return Chip(
      label: Text(label),
      backgroundColor: (isValid ? Colors.green : Colors.redAccent).withOpacity(
        0.12,
      ),
      labelStyle: TextStyle(
        color: isValid ? Colors.green : Colors.redAccent,
        fontWeight: FontWeight.w600,
      ),
      visualDensity: VisualDensity.compact,
      side: BorderSide(
        color: (isValid ? Colors.green : Colors.redAccent).withOpacity(0.5),
      ),
    );
  }

  bool _isValidKey(String key) => KeyMappings.isKnownKey(key);
}
