/// Central engine control panel for starting/stopping the engine.
///
/// Provides multi-device management, script selection, recording toggle,
/// and prominent start/stop controls with status indicators.
library;

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../models/device_state.dart';
import '../services/facade/keyrx_facade.dart';
import '../state/app_state.dart';
import '../models/runtime_config.dart';
import 'monitor_view.dart';
import 'run_controls_widgets.dart';

/// Engine running state.
enum EngineRunState { stopped, starting, running, stopping }

/// Central page for engine run controls.
class RunControlsPage extends StatefulWidget {
  const RunControlsPage({super.key});

  @override
  State<RunControlsPage> createState() => _RunControlsPageState();
}

class _RunControlsPageState extends State<RunControlsPage> {
  EngineRunState _runState = EngineRunState.stopped;
  bool _isRecording = false;
  String? _recordingPath;
  RuntimeConfig? _runtimeConfig;

  @override
  void initState() {
    super.initState();
    // Initial refresh of devices
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _refreshDevices();
    });
  }

  Future<void> _refreshDevices() async {
    final facade = Provider.of<KeyrxFacade>(context, listen: false);
    // Refreshing the registry updates the stream
    await facade.services.deviceRegistryService.refresh();

    // Also fetch runtime config to check for active slots
    final runtimeRes = await facade.services.runtimeService.getConfig();
    if (mounted && runtimeRes.data != null) {
      setState(() => _runtimeConfig = runtimeRes.data);
    }
  }

  Future<void> _toggleEngine() async {
    if (_runState == EngineRunState.running) {
      await _stopEngine();
    } else if (_runState == EngineRunState.stopped) {
      await _startEngine();
    }
  }

  Future<void> _startEngine() async {
    final appState = context.read<AppState>();
    if (!appState.initialized) {
      _showSnackBar('Engine not initialized', isError: true);
      return;
    }

    setState(() => _runState = EngineRunState.starting);

    final facade = Provider.of<KeyrxFacade>(context, listen: false);

    // Note: We no longer enforce a single "selected device" before starting.
    // The engine runs and processes inputs from all enabled devices.

    // Determine if we should start using active slots or fallback to a script
    bool hasActiveSlots = false;
    if (_runtimeConfig != null) {
      // Create a set of configured devices to match against
      final configuredDevices = _runtimeConfig!.devices
          .where((d) => d.slots.any((s) => s.active))
          .toList();

      if (configuredDevices.isNotEmpty) {
        // Technically this just means we have configured active slots.
        // The engine will use them if the device is connected.
        // We assume trust that the user intends to use the configuration.
        hasActiveSlots = true;
      }
    }

    String? scriptPath = appState.loadedScript;

    // If no script is loaded AND we don't have active slots, fallback to monitor.rhai
    if (scriptPath == null && !hasActiveSlots) {
      // No script loaded, and no active slots confgured.
      // Try to use/create default monitor.rhai for basic monitoring.
      try {
        final profilesPath = facade.services.storagePathResolver
            .resolveProfilesPath();
        final defaultPath =
            '$profilesPath${Platform.pathSeparator}monitor.rhai';

        final file = File(defaultPath);
        if (!file.existsSync()) {
          final saveRes = await facade.saveScript(
            defaultPath,
            '// Default Monitor Script\n// Auto-generated by KeyRx\n\nremap("CapsLock", "LeftCtrl");\n',
          );
          if (saveRes.isErr) {
            if (mounted) {
              _showSnackBar(
                'Failed to create default script: ${saveRes.errOrNull?.userMessage}',
                isError: true,
              );
            }
            setState(() => _runState = EngineRunState.stopped);
            return;
          }
        }

        // Now load it into AppState
        final loaded = await appState.loadScript(defaultPath);
        if (!loaded) {
          setState(() => _runState = EngineRunState.stopped);
          return; // appState handles error notification
        }
        scriptPath = defaultPath;

        if (mounted) {
          _showSnackBar('Loaded default monitor script');
        }
      } catch (e) {
        setState(() => _runState = EngineRunState.stopped);
        if (mounted) {
          _showSnackBar('Error preparing default script: $e', isError: true);
        }
        return;
      }
    }

    // Pass null if we are relying on slots and have no script
    // This allows KeyrxFacade.startEngine to start without loading a script file.
    final startResult = await facade.startEngine(scriptPath);
    await startResult.when(
      ok: (_) {
        if (mounted) {
          setState(() => _runState = EngineRunState.running);
          _showSnackBar('Engine started');
        }
      },
      err: (error) {
        setState(() => _runState = EngineRunState.stopped);
        if (mounted) {
          _showSnackBar(
            'Failed to start engine: ${error.userMessage}',
            isError: true,
          );
        }
      },
    );
  }

  Future<void> _stopEngine() async {
    setState(() => _runState = EngineRunState.stopping);

    final facade = Provider.of<KeyrxFacade>(context, listen: false);

    // Stop recording if active
    if (_isRecording) {
      await _stopRecording();
    }

    final result = await facade.stopEngine();

    result.when(
      ok: (_) {
        if (mounted) {
          setState(() => _runState = EngineRunState.stopped);
          _showSnackBar('Engine stopped');
        }
      },
      err: (error) {
        if (mounted) {
          setState(() => _runState = EngineRunState.stopped);
          _showSnackBar(
            'Failed to stop engine: ${error.userMessage}',
            isError: true,
          );
        }
      },
    );
  }

  Future<void> _toggleRecording() async {
    if (_isRecording) {
      await _stopRecording();
    } else {
      await _startRecording();
    }
  }

  Future<void> _startRecording() async {
    final timestamp = DateTime.now().toIso8601String().replaceAll(':', '-');
    final path = 'sessions/session_$timestamp.krx';

    final facade = Provider.of<KeyrxFacade>(context, listen: false);
    final bridge = facade.services.bridge;
    final result = bridge.startRecording(path);
    if (result.hasError) {
      _showSnackBar(
        'Failed to start recording: ${result.errorMessage}',
        isError: true,
      );
      return;
    }

    setState(() {
      _isRecording = true;
      _recordingPath = result.outputPath ?? path;
    });
    _showSnackBar('Recording started');
  }

  Future<void> _stopRecording() async {
    final facade = Provider.of<KeyrxFacade>(context, listen: false);
    final bridge = facade.services.bridge;
    final result = bridge.stopRecording();
    if (result.hasError) {
      _showSnackBar(
        'Failed to stop recording: ${result.errorMessage}',
        isError: true,
      );
      return;
    }

    final path = result.path;
    final events = result.eventCount;
    setState(() {
      _isRecording = false;
      _recordingPath = null;
    });
    _showSnackBar('Recording saved: $events events to $path');
  }

  void _showSnackBar(String message, {bool isError = false}) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: isError ? Colors.red : null,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    // Watch AppState for changes
    final appState = context.watch<AppState>();
    final isRunning = _runState == EngineRunState.running;
    final isBusy =
        _runState == EngineRunState.starting ||
        _runState == EngineRunState.stopping;

    return DefaultTabController(
      length: 2,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Dashboard'),
          bottom: const TabBar(
            tabs: [
              Tab(text: 'Controls', icon: Icon(Icons.tune)),
              Tab(text: 'Monitor', icon: Icon(Icons.monitor_heart)),
            ],
          ),
          actions: [
            // Start/Stop Action (Always visible)
            if (isRunning)
              FilledButton.icon(
                onPressed: _toggleEngine,
                icon: const Icon(Icons.stop),
                label: const Text('Stop'),
                style: FilledButton.styleFrom(
                  backgroundColor: Colors.red,
                  foregroundColor: Colors.white,
                ),
              )
            else
              FilledButton.icon(
                onPressed: _toggleEngine,
                icon: const Icon(Icons.play_arrow),
                label: const Text('Start'),
                style: FilledButton.styleFrom(
                  backgroundColor: Colors.green,
                  foregroundColor: Colors.white,
                ),
              ),
            const SizedBox(width: 8),
            IconButton(
              icon: const Icon(Icons.refresh),
              onPressed: _refreshDevices,
              tooltip: 'Refresh devices',
            ),
          ],
        ),
        body: TabBarView(
          children: [
            // Tab 1: Controls
            SingleChildScrollView(
              padding: const EdgeInsets.all(24),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  _buildStatusCard(appState, isRunning),
                  const SizedBox(height: 24),
                  _buildDeviceList(), // Refactored device list
                  const SizedBox(height: 16),
                  _buildScriptInfo(appState),
                  const SizedBox(height: 16),
                  _buildRecordingToggle(),
                  const SizedBox(height: 32),
                  _buildStartStopButton(isRunning, isBusy),
                ],
              ),
            ),

            // Tab 2: Monitor (Integrated)
            const MonitorView(),
          ],
        ),
      ),
    );
  }

  Widget _buildStatusCard(AppState appState, bool isRunning) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Status', style: Theme.of(context).textTheme.titleMedium),
            const SizedBox(height: 12),
            StatusIndicator(
              icon: Icons.power_settings_new,
              label: 'Engine',
              value: _runState.name.toUpperCase(),
              isActive: isRunning,
            ),
            const SizedBox(height: 8),
            StatusIndicator(
              icon: Icons.description,
              label: 'Script',
              value: appState.loadedScript != null
                  ? appState.loadedScript!.split(Platform.pathSeparator).last
                  : 'None loaded',
              isActive: appState.loadedScript != null,
            ),
            const SizedBox(height: 8),
            StatusIndicator(
              icon: Icons.fiber_manual_record,
              label: 'Recording',
              value: _isRecording ? 'Active' : 'Off',
              isActive: _isRecording,
              activeColor: Colors.red,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildDeviceList() {
    final facade = Provider.of<KeyrxFacade>(context, listen: false);

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                const Icon(Icons.keyboard, size: 20),
                const SizedBox(width: 8),
                Text('Devices', style: Theme.of(context).textTheme.titleMedium),
              ],
            ),
            const SizedBox(height: 12),
            StreamBuilder<List<DeviceState>>(
              stream: facade.services.deviceRegistryService.devicesStream,
              builder: (context, snapshot) {
                if (snapshot.hasError) {
                  return ErrorCard(
                    error: snapshot.error.toString(),
                    onRetry: _refreshDevices,
                  );
                }

                final devices = snapshot.data ?? [];

                if (devices.isEmpty) {
                  return const Text(
                    'No devices found. Connect a keyboard and refresh.',
                    style: TextStyle(color: Colors.grey),
                  );
                }

                return ListView.separated(
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  itemCount: devices.length,
                  separatorBuilder: (_, __) => const Divider(height: 1),
                  itemBuilder: (context, index) {
                    final device = devices[index];
                    return _buildDeviceListItem(device, facade);
                  },
                );
              },
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildDeviceListItem(DeviceState device, KeyrxFacade facade) {
    // Check for active slots in runtime config
    String profileText = device.profileId ?? 'No Profile';
    bool hasActiveSlots = false;

    if (_runtimeConfig != null) {
      DeviceSlots? match;
      for (final d in _runtimeConfig!.devices) {
        // Serial match is strict if config has serial, otherwise loose on VID:PID
        // But for connected devices (DeviceState), we want to find the specific config.
        // DeviceState ALWAYS has serial. DeviceInstanceId MAY have serial.
        // If DeviceInstanceId has serial, it must match.
        // If DeviceInstanceId has NO serial, it applies to all devices of that VID:PID.
        if (d.device.vendorId == device.identity.vendorId &&
            d.device.productId == device.identity.productId) {
          if (d.device.serial == null ||
              d.device.serial == device.identity.serialNumber) {
            match = d;
            break;
          }
        }
      }

      if (match != null) {
        final activeSlots = match.slots.where((s) => s.active).length;
        if (activeSlots > 0) {
          hasActiveSlots = true;
          profileText = 'Active ($activeSlots slots)';
        }
      }
    }

    final isActive =
        device.remapEnabled && (device.hasProfile || hasActiveSlots);
    final isPassthrough = !device.remapEnabled;

    Color statusColor = Colors.grey;
    if (isActive) {
      statusColor = Colors.green;
    } else if (device.remapEnabled && !hasActiveSlots && !device.hasProfile) {
      statusColor = Colors.orange; // Enabled but no profile
    }

    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: Row(
        children: [
          // Status Dot
          Container(
            width: 10,
            height: 10,
            decoration: BoxDecoration(
              color: statusColor,
              shape: BoxShape.circle,
            ),
          ),
          const SizedBox(width: 12),
          // Device Info
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  device.identity.displayName,
                  style: const TextStyle(fontWeight: FontWeight.w500),
                  overflow: TextOverflow.ellipsis,
                ),
                Text(
                  isPassthrough ? 'Passthrough' : profileText,
                  style: TextStyle(
                    fontSize: 12,
                    color: Theme.of(context).textTheme.bodySmall?.color,
                  ),
                ),
              ],
            ),
          ),
          // Remap Toggle
          Switch(
            value: device.remapEnabled,
            onChanged: (value) async {
              await facade.services.deviceRegistryService.toggleRemap(
                device.identity.toKey(),
                value,
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildScriptInfo(AppState appState) {
    final script = appState.loadedScript;

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                const Icon(Icons.description, size: 20),
                const SizedBox(width: 8),
                Text('Script', style: Theme.of(context).textTheme.titleMedium),
              ],
            ),
            const SizedBox(height: 12),
            if (script == null)
              const Text(
                'No script loaded. Use the Editor to load a script.',
                style: TextStyle(color: Colors.grey),
              )
            else
              Row(
                children: [
                  const Icon(Icons.check_circle, color: Colors.green, size: 16),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      script,
                      style: const TextStyle(fontFamily: 'monospace'),
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                ],
              ),
          ],
        ),
      ),
    );
  }

  Widget _buildRecordingToggle() {
    final isRunning = _runState == EngineRunState.running;

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Row(
          children: [
            Icon(
              Icons.fiber_manual_record,
              size: 20,
              color: _isRecording ? Colors.red : null,
            ),
            const SizedBox(width: 8),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Recording',
                    style: Theme.of(context).textTheme.titleMedium,
                  ),
                  if (_isRecording)
                    Text(
                      _recordingPath ?? 'Recording...',
                      style: Theme.of(context).textTheme.bodySmall?.copyWith(
                        fontFamily: 'monospace',
                        color: Colors.grey,
                      ),
                      overflow: TextOverflow.ellipsis,
                    ),
                ],
              ),
            ),
            Switch(
              value: _isRecording,
              onChanged: isRunning ? (_) => _toggleRecording() : null,
              activeTrackColor: Colors.red.withValues(alpha: 0.5),
              activeThumbColor: Colors.red,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildStartStopButton(bool isRunning, bool isBusy) {
    return StartStopButton(
      isRunning: isRunning,
      isBusy: isBusy,
      onPressed: _toggleEngine,
    );
  }
}
