//! Code generation templates for Dart FFI bindings
//!
//! This module provides string templates and rendering utilities for generating
//! Dart FFI function signatures, wrappers, and model classes.

use std::collections::HashMap;

/// Template context for placeholder replacement
pub type TemplateContext = HashMap<String, String>;

/// Create a new template context
pub fn context() -> TemplateContext {
    HashMap::new()
}

/// Render a template by replacing placeholders with context values.
///
/// Placeholders use the format `{{key}}` and are replaced with the
/// corresponding value from the context.
pub fn render(template: &str, ctx: &TemplateContext) -> String {
    let mut result = template.to_string();
    for (key, value) in ctx {
        let placeholder = format!("{{{{{}}}}}", key);
        result = result.replace(&placeholder, value);
    }
    result
}

// =============================================================================
// File Header Templates
// =============================================================================

/// Header for generated bindings file
pub const BINDINGS_FILE_HEADER: &str = r#"// GENERATED CODE - DO NOT EDIT
// This file was generated by the Dart binding generator.
// Generation time: {{timestamp}}
// Source contracts: core/src/ffi/contracts/*.ffi-contract.json
//
// To regenerate: cargo run --bin generate-dart-bindings
// Or: just gen-dart-bindings

// ignore_for_file: non_constant_identifier_names, unused_element, camel_case_types, unused_field

import 'dart:convert';
import 'dart:ffi';
import 'package:ffi/ffi.dart';
"#;

/// Header for generated models file
pub const MODELS_FILE_HEADER: &str = r#"// GENERATED CODE - DO NOT EDIT
// This file was generated by the Dart binding generator.
// Generation time: {{timestamp}}
// Source contracts: core/src/ffi/contracts/*.ffi-contract.json
//
// To regenerate: cargo run --bin generate-dart-bindings
// Or: just gen-dart-bindings

// ignore_for_file: non_constant_identifier_names
"#;

// =============================================================================
// FFI Signature Templates
// =============================================================================

/// Template for native FFI function typedef (C signature)
///
/// Placeholders:
/// - `{{function_name}}` - Full FFI function name (e.g., keyrx_config_save_profile)
/// - `{{return_type}}` - FFI return type (e.g., Pointer<Utf8>)
/// - `{{native_params}}` - Native parameter list (e.g., Pointer<Utf8> json, Pointer<Pointer<Utf8>> error)
pub const NATIVE_TYPEDEF_TEMPLATE: &str =
    "typedef _{{function_name}}_native = {{return_type}} Function({{native_params}});";

/// Template for Dart FFI function typedef (Dart signature)
///
/// Placeholders:
/// - `{{function_name}}` - Full FFI function name
/// - `{{return_type}}` - Dart FFI return type
/// - `{{dart_params}}` - Dart parameter list
pub const DART_TYPEDEF_TEMPLATE: &str =
    "typedef _{{function_name}} = {{return_type}} Function({{dart_params}});";

/// Template for function pointer lookup
///
/// Placeholders:
/// - `{{function_name}}` - Full FFI function name
/// - `{{lookup_name}}` - Name for the late final variable
pub const FUNCTION_POINTER_TEMPLATE: &str = r#"late final _{{lookup_name}} = _lib
    .lookup<NativeFunction<_{{function_name}}_native>>('{{function_name}}')
    .asFunction<_{{function_name}}>();"#;

// =============================================================================
// Wrapper Function Templates
// =============================================================================

/// Template for wrapper function with error handling and string return
///
/// Placeholders:
/// - `{{dart_function_name}}` - Dart function name (camelCase)
/// - `{{dart_return_type}}` - Dart return type (e.g., String, void)
/// - `{{dart_params_signature}}` - Dart parameter signature (e.g., String json, int count)
/// - `{{param_conversions}}` - Code to convert Dart params to FFI (e.g., final jsonPtr = json.toNativeUtf8();)
/// - `{{ffi_call_args}}` - Arguments to pass to FFI function
/// - `{{param_frees}}` - Code to free allocated parameters
/// - `{{lookup_name}}` - Name of the function pointer variable
/// - `{{result_conversion}}` - Code to convert result to Dart type
/// - `{{free_result}}` - Code to free the result pointer (if needed)
pub const WRAPPER_FUNCTION_WITH_ERROR_TEMPLATE: &str = r#"/// {{doc_comment}}
{{dart_return_type}} {{dart_function_name}}({{dart_params_signature}}) {
  final errorPtr = calloc<Pointer<Utf8>>();
  try {
{{param_conversions}}
    final resultPtr = _{{lookup_name}}({{ffi_call_args}});
{{param_frees}}
    if (errorPtr.value.address != 0) {
      final error = errorPtr.value.toDartString();
      calloc.free(errorPtr.value);
      throw FfiException(error);
    }
{{result_conversion}}
  } finally {
    calloc.free(errorPtr);
  }
}"#;

/// Template for wrapper function without error handling (void return, no error ptr)
///
/// Placeholders:
/// - `{{dart_function_name}}` - Dart function name (camelCase)
/// - `{{dart_params_signature}}` - Dart parameter signature
/// - `{{param_conversions}}` - Code to convert Dart params to FFI
/// - `{{ffi_call_args}}` - Arguments to pass to FFI function
/// - `{{param_frees}}` - Code to free allocated parameters
/// - `{{lookup_name}}` - Name of the function pointer variable
pub const WRAPPER_FUNCTION_SIMPLE_TEMPLATE: &str = r#"/// {{doc_comment}}
void {{dart_function_name}}({{dart_params_signature}}) {
{{param_conversions}}
  _{{lookup_name}}({{ffi_call_args}});
{{param_frees}}
}"#;

/// Template for parameter conversion (string to native)
pub const PARAM_TO_NATIVE_UTF8: &str =
    "    final {{param_name}}Ptr = {{param_name}}.toNativeUtf8();";

/// Template for freeing a native string parameter
pub const PARAM_FREE_UTF8: &str = "    calloc.free({{param_name}}Ptr);";

/// Template for string result conversion
pub const RESULT_STRING_CONVERSION: &str = r#"    if (resultPtr.address == 0) {
      throw FfiException('Unexpected null return from FFI');
    }
    final result = resultPtr.toDartString();
    _keyrx_free_string(resultPtr);
    return result;"#;

/// Template for JSON-decoded result conversion
///
/// Placeholders:
/// - `{{dart_type}}` - The Dart type to return (e.g., Map<String, dynamic>)
pub const RESULT_JSON_DECODE_CONVERSION: &str = r#"    if (resultPtr.address == 0) {
      throw FfiException('Unexpected null return from FFI');
    }
    final resultJson = resultPtr.toDartString();
    _keyrx_free_string(resultPtr);
    return jsonDecode(resultJson) as {{dart_type}};"#;

/// Template for model class result conversion
///
/// Placeholders:
/// - `{{class_name}}` - The Dart class name (e.g., HardwareProfile)
pub const RESULT_MODEL_CONVERSION: &str = r#"    if (resultPtr.address == 0) {
      throw FfiException('Unexpected null return from FFI');
    }
    final resultJson = resultPtr.toDartString();
    _keyrx_free_string(resultPtr);
    return {{class_name}}.fromJson(jsonDecode(resultJson) as Map<String, dynamic>);"#;

/// Template for void return (no result conversion needed)
pub const RESULT_VOID_TEMPLATE: &str = "    // void return - no result conversion";

// =============================================================================
// Model Class Templates
// =============================================================================

/// Template for a Dart model class
///
/// Placeholders:
/// - `{{class_name}}` - Class name in PascalCase
/// - `{{fields}}` - Field declarations (final String name;)
/// - `{{constructor_params}}` - Constructor parameters (required this.name,)
/// - `{{from_json_body}}` - fromJson factory body
/// - `{{to_json_body}}` - toJson method body
pub const MODEL_CLASS_TEMPLATE: &str = r#"/// {{doc_comment}}
class {{class_name}} {
{{fields}}

  {{class_name}}({
{{constructor_params}}
  });

  factory {{class_name}}.fromJson(Map<String, dynamic> json) {
    return {{class_name}}(
{{from_json_body}}
    );
  }

  Map<String, dynamic> toJson() {
    return {
{{to_json_body}}
    };
  }
}"#;

/// Template for a model field declaration
///
/// Placeholders:
/// - `{{dart_type}}` - Dart type (e.g., String, int, String?)
/// - `{{field_name}}` - Field name in camelCase
pub const MODEL_FIELD_TEMPLATE: &str = "  final {{dart_type}} {{field_name}};";

/// Template for a required constructor parameter
pub const CONSTRUCTOR_PARAM_REQUIRED: &str = "    required this.{{field_name}},";

/// Template for an optional constructor parameter
pub const CONSTRUCTOR_PARAM_OPTIONAL: &str = "    this.{{field_name}},";

/// Template for fromJson field assignment (required field)
///
/// Placeholders:
/// - `{{field_name}}` - Dart field name
/// - `{{json_key}}` - JSON key (snake_case)
/// - `{{dart_cast}}` - Dart type cast (e.g., as String, as int)
pub const FROM_JSON_REQUIRED: &str = "      {{field_name}}: json['{{json_key}}'] {{dart_cast}},";

/// Template for fromJson field assignment (optional field)
pub const FROM_JSON_OPTIONAL: &str =
    "      {{field_name}}: json['{{json_key}}'] {{dart_cast_nullable}},";

/// Template for toJson field
pub const TO_JSON_FIELD: &str = "      '{{json_key}}': {{field_name}},";

// =============================================================================
// FFI Exception Class
// =============================================================================

/// Template for the FfiException class
pub const FFI_EXCEPTION_CLASS: &str = r#"/// Exception thrown when FFI calls fail
class FfiException implements Exception {
  final String message;

  FfiException(this.message);

  @override
  String toString() => 'FfiException: $message';
}"#;

// =============================================================================
// Bindings Class Template
// =============================================================================

/// Template for the bindings class that holds all FFI functions
///
/// Placeholders:
/// - `{{class_name}}` - Class name (e.g., KeyrxBindings)
/// - `{{typedefs}}` - All typedef declarations
/// - `{{function_pointers}}` - All function pointer lookups
/// - `{{wrapper_functions}}` - All wrapper function implementations
pub const BINDINGS_CLASS_TEMPLATE: &str = r#"/// FFI bindings for {{domain}} domain
class {{class_name}} {
  final DynamicLibrary _lib;

  {{class_name}}(this._lib);

  // Free string function lookup
  late final _keyrx_free_string = _lib
      .lookup<NativeFunction<Void Function(Pointer<Utf8>)>>('keyrx_free_string')
      .asFunction<void Function(Pointer<Utf8>)>();

{{typedefs}}

{{function_pointers}}

{{wrapper_functions}}
}"#;

// =============================================================================
// Helper Functions
// =============================================================================

/// Convert a snake_case name to camelCase
pub fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;

    for (i, c) in s.chars().enumerate() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else if i == 0 {
            result.push(c.to_ascii_lowercase());
        } else {
            result.push(c);
        }
    }

    result
}

/// Convert a snake_case name to PascalCase
pub fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in s.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}

/// Convert a camelCase or PascalCase name to snake_case
pub fn to_snake_case(s: &str) -> String {
    let mut result = String::new();

    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        } else {
            result.push(c);
        }
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_render_simple_placeholder() {
        let mut ctx = context();
        ctx.insert("name".to_string(), "test".to_string());
        assert_eq!(render("Hello {{name}}", &ctx), "Hello test");
    }

    #[test]
    fn test_render_multiple_placeholders() {
        let mut ctx = context();
        ctx.insert("type".to_string(), "String".to_string());
        ctx.insert("name".to_string(), "value".to_string());
        assert_eq!(render("{{type}} {{name}}", &ctx), "String value");
    }

    #[test]
    fn test_render_repeated_placeholder() {
        let mut ctx = context();
        ctx.insert("x".to_string(), "foo".to_string());
        assert_eq!(render("{{x}} and {{x}}", &ctx), "foo and foo");
    }

    #[test]
    fn test_render_missing_placeholder() {
        let ctx = context();
        assert_eq!(render("Hello {{name}}", &ctx), "Hello {{name}}");
    }

    #[test]
    fn test_to_camel_case() {
        assert_eq!(to_camel_case("hello_world"), "helloWorld");
        assert_eq!(
            to_camel_case("save_hardware_profile"),
            "saveHardwareProfile"
        );
        assert_eq!(to_camel_case("already"), "already");
        assert_eq!(to_camel_case("a_b_c"), "aBC");
    }

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("hello_world"), "HelloWorld");
        assert_eq!(to_pascal_case("hardware_profile"), "HardwareProfile");
        assert_eq!(to_pascal_case("already"), "Already");
    }

    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("HelloWorld"), "hello_world");
        assert_eq!(to_snake_case("HardwareProfile"), "hardware_profile");
        assert_eq!(to_snake_case("already"), "already");
        assert_eq!(to_snake_case("vendorId"), "vendor_id");
    }

    #[test]
    fn test_native_typedef_template() {
        let mut ctx = context();
        ctx.insert("function_name".to_string(), "keyrx_config_save".to_string());
        ctx.insert("return_type".to_string(), "Pointer<Utf8>".to_string());
        ctx.insert(
            "native_params".to_string(),
            "Pointer<Utf8> json, Pointer<Pointer<Utf8>> error".to_string(),
        );

        let result = render(NATIVE_TYPEDEF_TEMPLATE, &ctx);
        assert!(result.contains("typedef _keyrx_config_save_native"));
        assert!(result.contains("Pointer<Utf8> Function"));
        assert!(result.contains("Pointer<Utf8> json"));
    }

    #[test]
    fn test_dart_typedef_template() {
        let mut ctx = context();
        ctx.insert("function_name".to_string(), "keyrx_config_save".to_string());
        ctx.insert("return_type".to_string(), "Pointer<Utf8>".to_string());
        ctx.insert(
            "dart_params".to_string(),
            "Pointer<Utf8> json, Pointer<Pointer<Utf8>> error".to_string(),
        );

        let result = render(DART_TYPEDEF_TEMPLATE, &ctx);
        assert!(result.contains("typedef _keyrx_config_save ="));
        assert!(result.contains("Pointer<Utf8> Function"));
    }

    #[test]
    fn test_function_pointer_template() {
        let mut ctx = context();
        ctx.insert("function_name".to_string(), "keyrx_config_save".to_string());
        ctx.insert("lookup_name".to_string(), "save".to_string());

        let result = render(FUNCTION_POINTER_TEMPLATE, &ctx);
        assert!(result.contains("late final _save ="));
        assert!(result.contains("NativeFunction<_keyrx_config_save_native>"));
        assert!(result.contains("'keyrx_config_save'"));
        assert!(result.contains(".asFunction<_keyrx_config_save>()"));
    }

    #[test]
    fn test_model_class_template_structure() {
        let mut ctx = context();
        ctx.insert("class_name".to_string(), "Profile".to_string());
        ctx.insert("doc_comment".to_string(), "A user profile".to_string());
        ctx.insert("fields".to_string(), "  final String name;".to_string());
        ctx.insert(
            "constructor_params".to_string(),
            "    required this.name,".to_string(),
        );
        ctx.insert(
            "from_json_body".to_string(),
            "      name: json['name'] as String,".to_string(),
        );
        ctx.insert(
            "to_json_body".to_string(),
            "      'name': name,".to_string(),
        );

        let result = render(MODEL_CLASS_TEMPLATE, &ctx);
        assert!(result.contains("class Profile {"));
        assert!(result.contains("final String name;"));
        assert!(result.contains("Profile({"));
        assert!(result.contains("factory Profile.fromJson"));
        assert!(result.contains("Map<String, dynamic> toJson()"));
    }

    #[test]
    fn test_ffi_exception_class() {
        assert!(FFI_EXCEPTION_CLASS.contains("class FfiException"));
        assert!(FFI_EXCEPTION_CLASS.contains("final String message"));
        assert!(FFI_EXCEPTION_CLASS.contains("FfiException(this.message)"));
    }
}
