/// Profiler page for viewing flame graphs and allocation reports.
///
/// Allows loading profiling artifacts generated by `keyrx bench` with
/// `--flamegraph` and `--allocations` flags. Flame graphs are rendered from
/// SVG, and allocation reports are summarized with hot spot breakdowns.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

class ProfilerPage extends StatefulWidget {
  const ProfilerPage({super.key});

  @override
  State<ProfilerPage> createState() => _ProfilerPageState();
}

class _ProfilerPageState extends State<ProfilerPage> {
  final _flamegraphPathController = TextEditingController(
    text: 'bench-flamegraph.svg',
  );
  final _allocationPathController = TextEditingController(
    text: 'bench-allocations.json',
  );

  String? _flamegraphSvg;
  String? _flamegraphError;
  bool _flamegraphLoading = false;

  AllocationReportView? _allocationReport;
  String? _allocationError;
  bool _allocationLoading = false;

  @override
  void dispose() {
    _flamegraphPathController.dispose();
    _allocationPathController.dispose();
    super.dispose();
  }

  Future<void> _loadFlamegraph() async {
    final path = _flamegraphPathController.text.trim();
    setState(() {
      _flamegraphLoading = true;
      _flamegraphError = null;
    });

    try {
      final svg = await _readFile(path);
      if (!mounted) return;
      setState(() {
        _flamegraphSvg = svg;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _flamegraphSvg = null;
        _flamegraphError = 'Failed to load flame graph: $e';
      });
    } finally {
      if (mounted) {
        setState(() {
          _flamegraphLoading = false;
        });
      }
    }
  }

  Future<void> _loadAllocationReport() async {
    final path = _allocationPathController.text.trim();
    setState(() {
      _allocationLoading = true;
      _allocationError = null;
    });

    try {
      final jsonString = await _readFile(path);
      final decoded = json.decode(jsonString) as Map<String, dynamic>;
      final report = AllocationReportView.fromJson(decoded);

      if (!mounted) return;
      setState(() {
        _allocationReport = report;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _allocationReport = null;
        _allocationError = 'Failed to load allocation report: $e';
      });
    } finally {
      if (mounted) {
        setState(() {
          _allocationLoading = false;
        });
      }
    }
  }

  Future<String> _readFile(String path) async {
    final file = File(path);
    if (!await file.exists()) {
      throw FileSystemException('File not found', path);
    }
    return file.readAsString();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Profiler')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            _buildFlamegraphCard(context),
            const SizedBox(height: 20),
            _buildAllocationCard(context),
          ],
        ),
      ),
    );
  }

  Widget _buildFlamegraphCard(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                const Icon(Icons.local_fire_department_outlined),
                const SizedBox(width: 8),
                Text(
                  'Flame Graph',
                  style: Theme.of(context).textTheme.titleMedium,
                ),
                const Spacer(),
                FilledButton.icon(
                  onPressed: _flamegraphLoading ? null : _loadFlamegraph,
                  icon: _flamegraphLoading
                      ? const SizedBox(
                          width: 16,
                          height: 16,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.white,
                          ),
                        )
                      : const Icon(Icons.refresh),
                  label: Text(_flamegraphLoading ? 'Loading...' : 'Load'),
                ),
              ],
            ),
            const SizedBox(height: 12),
            TextField(
              controller: _flamegraphPathController,
              decoration: const InputDecoration(
                labelText: 'SVG path',
                hintText: 'bench-flamegraph.svg',
                prefixIcon: Icon(Icons.insert_drive_file_outlined),
              ),
            ),
            const SizedBox(height: 12),
            _buildFlamegraphContent(context),
          ],
        ),
      ),
    );
  }

  Widget _buildFlamegraphContent(BuildContext context) {
    if (_flamegraphLoading) {
      return const Center(child: CircularProgressIndicator());
    }

    if (_flamegraphError != null) {
      return _buildErrorBanner(context, _flamegraphError!);
    }

    if (_flamegraphSvg == null) {
      return _buildPlaceholder(
        context,
        icon: Icons.insert_chart,
        title: 'No flame graph loaded',
        message:
            'Run `keyrx bench --flamegraph` to generate bench-flamegraph.svg, '
            'then load it here.',
      );
    }

    return Container(
      height: 420,
      width: double.infinity,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12),
        color: Theme.of(
          context,
        ).colorScheme.surfaceContainerHighest.withValues(alpha: 0.2),
        border: Border.all(color: Colors.grey.shade800),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(12),
        child: InteractiveViewer(
          minScale: 0.5,
          maxScale: 4,
          child: SvgPicture.string(
            _flamegraphSvg!,
            allowDrawingOutsideViewBox: true,
            fit: BoxFit.contain,
          ),
        ),
      ),
    );
  }

  Widget _buildAllocationCard(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                const Icon(Icons.storage_outlined),
                const SizedBox(width: 8),
                Text(
                  'Allocation Report',
                  style: Theme.of(context).textTheme.titleMedium,
                ),
                const Spacer(),
                FilledButton.icon(
                  onPressed: _allocationLoading ? null : _loadAllocationReport,
                  icon: _allocationLoading
                      ? const SizedBox(
                          width: 16,
                          height: 16,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.white,
                          ),
                        )
                      : const Icon(Icons.refresh),
                  label: Text(_allocationLoading ? 'Loading...' : 'Load'),
                ),
              ],
            ),
            const SizedBox(height: 12),
            TextField(
              controller: _allocationPathController,
              decoration: const InputDecoration(
                labelText: 'Report path',
                hintText: 'bench-allocations.json',
                prefixIcon: Icon(Icons.description_outlined),
              ),
            ),
            const SizedBox(height: 12),
            _buildAllocationContent(context),
          ],
        ),
      ),
    );
  }

  Widget _buildAllocationContent(BuildContext context) {
    if (_allocationLoading) {
      return const Center(child: CircularProgressIndicator());
    }

    if (_allocationError != null) {
      return _buildErrorBanner(context, _allocationError!);
    }

    final report = _allocationReport;
    if (report == null) {
      return _buildPlaceholder(
        context,
        icon: Icons.bar_chart_outlined,
        title: 'No allocation report loaded',
        message:
            'Run `keyrx bench --allocations` to write bench-allocations.json, '
            'then load it here.',
      );
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Wrap(
          spacing: 12,
          runSpacing: 12,
          children: [
            _buildStatChip(
              label: 'Total allocated',
              value: _formatBytes(report.stats.totalAllocated),
              icon: Icons.cloud_upload_outlined,
            ),
            _buildStatChip(
              label: 'Peak usage',
              value: _formatBytes(report.stats.peakUsage),
              icon: Icons.show_chart,
            ),
            _buildStatChip(
              label: 'Current usage',
              value: _formatBytes(report.stats.currentUsage),
              icon: Icons.memory,
            ),
            _buildStatChip(
              label: 'Allocations',
              value: _formatNumber(report.stats.allocationCount),
              icon: Icons.add_circle_outline,
            ),
            _buildStatChip(
              label: 'Frees',
              value: _formatNumber(report.stats.freeCount),
              icon: Icons.remove_circle_outline,
            ),
          ],
        ),
        const SizedBox(height: 12),
        if (report.summary != null)
          _buildSummaryCards(context, report.summary!),
        if (report.warnings.isNotEmpty) ...[
          const SizedBox(height: 12),
          _buildWarnings(context, report.warnings),
        ],
        const SizedBox(height: 12),
        _buildHotSpots(context, report.hotSpots),
      ],
    );
  }

  Widget _buildSummaryCards(
    BuildContext context,
    AllocationSummaryView summary,
  ) {
    return Wrap(
      spacing: 12,
      runSpacing: 12,
      children: [
        _buildStatChip(
          label: 'Avg allocation',
          value: _formatBytes(summary.avgAllocationSize),
          icon: Icons.speed_outlined,
        ),
        _buildStatChip(
          label: 'Efficiency',
          value: '${_formatPercent(summary.memoryEfficiency * 100)} freed',
          icon: Icons.check_circle_outline,
        ),
        _buildStatChip(
          label: 'Hot spots',
          value: _formatNumber(summary.hotSpotCount),
          icon: Icons.whatshot_outlined,
        ),
        _buildStatChip(
          label: 'Largest site',
          value: _formatBytes(summary.largestSiteBytes),
          icon: Icons.storage,
        ),
      ],
    );
  }

  Widget _buildWarnings(BuildContext context, List<String> warnings) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('Warnings', style: Theme.of(context).textTheme.titleSmall),
        const SizedBox(height: 8),
        ...warnings.map(
          (w) => Card(
            color: Colors.orange.shade100.withValues(alpha: 0.15),
            child: Padding(
              padding: const EdgeInsets.all(12),
              child: Row(
                children: [
                  const Icon(
                    Icons.warning_amber_outlined,
                    color: Colors.orange,
                  ),
                  const SizedBox(width: 8),
                  Expanded(child: Text(w)),
                ],
              ),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildHotSpots(
    BuildContext context,
    List<AllocationHotSpotView> hotSpots,
  ) {
    if (hotSpots.isEmpty) {
      return _buildPlaceholder(
        context,
        icon: Icons.check_circle_outline,
        title: 'No hot spots detected',
        message: 'Run longer benchmarks or lower the hot spot threshold.',
      );
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('Hot Spots', style: Theme.of(context).textTheme.titleSmall),
        const SizedBox(height: 8),
        ...hotSpots.map(_buildHotSpotTile),
      ],
    );
  }

  Widget _buildHotSpotTile(AllocationHotSpotView site) {
    return Card(
      child: ExpansionTile(
        title: Text(site.location),
        subtitle: Text(
          '${_formatBytes(site.totalBytes)} • '
          '${_formatNumber(site.count)} allocs • '
          '${_formatPercent(site.percentage)}',
        ),
        childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 12),
        children: [
          if (site.stackTrace.isNotEmpty)
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Stack trace (${site.stackTrace.length} frames)',
                  style: Theme.of(context).textTheme.bodySmall,
                ),
                const SizedBox(height: 8),
                ...site.stackTrace.map(
                  (frame) => Text(
                    frame,
                    style: Theme.of(
                      context,
                    ).textTheme.bodySmall?.copyWith(color: Colors.grey[300]),
                  ),
                ),
              ],
            )
          else
            Text(
              'Stack trace not captured for this site.',
              style: Theme.of(context).textTheme.bodySmall,
            ),
        ],
      ),
    );
  }

  Widget _buildStatChip({
    required String label,
    required String value,
    required IconData icon,
  }) {
    return Chip(
      avatar: Icon(icon, size: 18),
      label: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(label, style: const TextStyle(fontSize: 12)),
          Text(value, style: const TextStyle(fontWeight: FontWeight.bold)),
        ],
      ),
    );
  }

  Widget _buildErrorBanner(BuildContext context, String message) {
    final scheme = Theme.of(context).colorScheme;
    return Card(
      color: scheme.errorContainer,
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Row(
          children: [
            Icon(Icons.error_outline, color: scheme.error),
            const SizedBox(width: 12),
            Expanded(
              child: Text(
                message,
                style: TextStyle(color: scheme.onErrorContainer),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildPlaceholder(
    BuildContext context, {
    required IconData icon,
    required String title,
    required String message,
  }) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(vertical: 24),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12),
        color: Colors.grey.shade900,
        border: Border.all(color: Colors.grey.shade800),
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(icon, size: 36, color: Colors.grey.shade500),
          const SizedBox(height: 8),
          Text(title, style: Theme.of(context).textTheme.titleSmall),
          const SizedBox(height: 4),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 12),
            child: Text(
              message,
              textAlign: TextAlign.center,
              style: Theme.of(context).textTheme.bodySmall,
            ),
          ),
        ],
      ),
    );
  }

  String _formatBytes(num bytes) {
    const units = ['B', 'KB', 'MB', 'GB'];
    var value = bytes.toDouble();
    var unitIndex = 0;

    while (value >= 1024 && unitIndex < units.length - 1) {
      value /= 1024;
      unitIndex++;
    }

    return '${value.toStringAsFixed(value < 10 ? 2 : 1)} ${units[unitIndex]}';
  }

  String _formatPercent(num value) => '${value.toStringAsFixed(1)}%';

  String _formatNumber(num value) {
    final str = value.toInt().toString();
    final regex = RegExp(r'(\d)(?=(\d{3})+(?!\d))');
    return str.replaceAllMapped(regex, (match) => '${match[1]},');
  }
}

class AllocationReportView {
  const AllocationReportView({
    required this.stats,
    required this.hotSpots,
    required this.warnings,
    this.summary,
  });

  factory AllocationReportView.fromJson(Map<String, dynamic> json) {
    final hotSpotsJson = json['hot_spots'] as List<dynamic>? ?? const [];
    return AllocationReportView(
      stats: AllocationStatsView.fromJson(
        json['stats'] as Map<String, dynamic>?,
      ),
      hotSpots: hotSpotsJson
          .map(
            (entry) =>
                AllocationHotSpotView.fromJson(entry as Map<String, dynamic>?),
          )
          .toList(),
      warnings: (json['warnings'] as List<dynamic>? ?? const [])
          .map((w) => '$w')
          .toList(),
      summary: AllocationSummaryView.fromJson(
        json['summary'] as Map<String, dynamic>?,
      ),
    );
  }

  final AllocationStatsView stats;
  final List<AllocationHotSpotView> hotSpots;
  final List<String> warnings;
  final AllocationSummaryView? summary;
}

class AllocationStatsView {
  const AllocationStatsView({
    required this.totalAllocated,
    required this.totalFreed,
    required this.peakUsage,
    required this.currentUsage,
    required this.allocationCount,
    required this.freeCount,
  });

  factory AllocationStatsView.fromJson(Map<String, dynamic>? json) {
    final data = json ?? const <String, dynamic>{};
    return AllocationStatsView(
      totalAllocated: (data['total_allocated'] as num?)?.toInt() ?? 0,
      totalFreed: (data['total_freed'] as num?)?.toInt() ?? 0,
      peakUsage: (data['peak_usage'] as num?)?.toInt() ?? 0,
      currentUsage: (data['current_usage'] as num?)?.toInt() ?? 0,
      allocationCount: (data['allocation_count'] as num?)?.toInt() ?? 0,
      freeCount: (data['free_count'] as num?)?.toInt() ?? 0,
    );
  }

  final int totalAllocated;
  final int totalFreed;
  final int peakUsage;
  final int currentUsage;
  final int allocationCount;
  final int freeCount;
}

class AllocationHotSpotView {
  const AllocationHotSpotView({
    required this.location,
    required this.count,
    required this.totalBytes,
    required this.stackTrace,
    required this.percentage,
  });

  factory AllocationHotSpotView.fromJson(Map<String, dynamic>? json) {
    final data = json ?? const <String, dynamic>{};
    return AllocationHotSpotView(
      location: data['location']?.toString() ?? 'Unknown location',
      count: (data['count'] as num?)?.toInt() ?? 0,
      totalBytes: (data['total_bytes'] as num?)?.toInt() ?? 0,
      stackTrace: (data['stack_trace'] as List<dynamic>? ?? const [])
          .map((frame) => frame.toString())
          .toList(),
      percentage: (data['percentage'] as num?)?.toDouble() ?? 0,
    );
  }

  final String location;
  final int count;
  final int totalBytes;
  final List<String> stackTrace;
  final double percentage;
}

class AllocationSummaryView {
  const AllocationSummaryView({
    required this.avgAllocationSize,
    required this.memoryEfficiency,
    required this.hotSpotCount,
    required this.largestSiteBytes,
  });

  factory AllocationSummaryView.fromJson(Map<String, dynamic>? json) {
    final data = json ?? const <String, dynamic>{};
    return AllocationSummaryView(
      avgAllocationSize: (data['avg_allocation_size'] as num?)?.toInt() ?? 0,
      memoryEfficiency: (data['memory_efficiency'] as num?)?.toDouble() ?? 0,
      hotSpotCount: (data['hot_spot_count'] as num?)?.toInt() ?? 0,
      largestSiteBytes: (data['largest_site_bytes'] as num?)?.toInt() ?? 0,
    );
  }

  final int avgAllocationSize;
  final double memoryEfficiency;
  final int hotSpotCount;
  final int largestSiteBytes;
}
