#![allow(clippy::missing_safety_doc)]
#![allow(clippy::expect_used)]
#![allow(clippy::unwrap_used)]

use crate::config::models::DeviceInstanceId;
use crate::definitions::DeviceDefinitionLibrary;
use crate::ffi::domains::engine::global_event_registry;
use crate::ffi::error::{serialize_ffi_result, FfiError, FfiResult};
use crate::ffi::events::EventType;
use crate::ffi::runtime::{
    clear_revolutionary_runtime, set_revolutionary_runtime, RevolutionaryRuntime,
};
use crate::registry::{DeviceRegistry, ProfileRegistry};
use std::ffi::{c_char, CStr, CString};
use std::ptr;
use std::sync::{Arc, Mutex};

// Re-export specific helpers for other FFI modules
pub(crate) fn parse_c_string(ptr: *const c_char, param_name: &str) -> FfiResult<String> {
    if ptr.is_null() {
        return Err(FfiError::null_pointer(param_name));
    }
    unsafe {
        CStr::from_ptr(ptr)
            .to_str()
            .map(|s| s.to_string())
            .map_err(|_| FfiError::invalid_utf8(param_name))
    }
}

pub(crate) fn parse_device_json(json_str: &str) -> FfiResult<DeviceInstanceId> {
    serde_json::from_str(json_str)
        .map_err(|e| FfiError::invalid_input(format!("Invalid device JSON: {}", e)))
}

fn init_revolutionary_runtime() {
    // Initialize with default/empty components for now.
    // In a real app complexity, this would load config from disk.
    let (registry, _rx) = DeviceRegistry::new();
    let profiles = Arc::new(ProfileRegistry::new());
    let definitions = Arc::new(DeviceDefinitionLibrary::new());
    let rhai = crate::scripting::RhaiRuntime::new().expect("failed to initialize rhai runtime");
    let rhai_runtime = Arc::new(Mutex::new(rhai));

    let runtime = RevolutionaryRuntime::new(registry, profiles, definitions, rhai_runtime);
    let _ = set_revolutionary_runtime(runtime);
}

#[no_mangle]
pub unsafe extern "C" fn keyrx_init() -> i32 {
    init_revolutionary_runtime();
    0
}

#[no_mangle]
pub unsafe extern "C" fn keyrx_version() -> *mut c_char {
    let version = env!("CARGO_PKG_VERSION");
    CString::new(version).unwrap().into_raw()
}

#[no_mangle]
pub unsafe extern "C" fn keyrx_free_string(s: *mut c_char) {
    if !s.is_null() {
        let _ = CString::from_raw(s);
    }
}

#[no_mangle]
pub unsafe extern "C" fn keyrx_last_error() -> *mut c_char {
    // This is a placeholder. Real implementation might use thread-local storage
    // or a global error registry if needed for legacy C interop style.
    // For now returning null or empty string as we use Result JSON returns.
    ptr::null_mut()
}

#[no_mangle]
pub unsafe extern "C" fn keyrx_register_event_callback(
    event_type: i32,
    callback: Option<unsafe extern "C" fn(*const u8, usize)>,
) -> i32 {
    let event_type = match EventType::from_i32(event_type) {
        Some(t) => t,
        None => return -1,
    };

    global_event_registry().register(event_type, callback);
    0
}

#[no_mangle]
pub unsafe extern "C" fn keyrx_protocol_version() -> u32 {
    1
}

/// Get FFI introspection metadata (developer tools)
///
/// Returns JSON with all available FFI functions, parameters, and events.
/// This enables runtime discovery of FFI capabilities.
#[no_mangle]
pub unsafe extern "C" fn keyrx_introspection_metadata() -> *mut c_char {
    use crate::ffi::introspection::{generate_introspection_data, init_contracts};

    // Initialize contracts if not already done
    if let Err(e) = init_contracts() {
        // Already initialized is OK
        if !e.to_string().contains("already initialized") {
            let err_result: FfiResult<()> = Err(e);
            return match serialize_ffi_result(&err_result) {
                Ok(json) => CString::new(json).unwrap_or_default().into_raw(),
                Err(_) => ptr::null_mut(),
            };
        }
    }

    // Generate introspection data
    let result = generate_introspection_data();
    match serialize_ffi_result(&result) {
        Ok(json) => CString::new(json).unwrap_or_default().into_raw(),
        Err(_) => ptr::null_mut(),
    }
}

#[no_mangle]
pub unsafe extern "C" fn keyrx_set_config_root(path: *const c_char) -> i32 {
    let path_str = match parse_c_string(path, "path") {
        Ok(s) => s,
        Err(_) => return -1,
    };

    crate::config::set_config_root(std::path::PathBuf::from(path_str));
    0
}

#[no_mangle]
pub unsafe extern "C" fn keyrx_revolutionary_runtime_init() -> i32 {
    init_revolutionary_runtime();
    0
}

#[no_mangle]
pub unsafe extern "C" fn keyrx_revolutionary_runtime_shutdown() -> i32 {
    let _ = clear_revolutionary_runtime();
    0
}

#[no_mangle]
pub unsafe extern "C" fn keyrx_free_event_payload(ptr: *mut u8, len: usize) {
    if !ptr.is_null() && len > 0 {
        let slice = std::ptr::slice_from_raw_parts_mut(ptr, len);
        let _ = Box::from_raw(slice);
    }
}

// Config FFI exports are now generated by the keyrx_ffi macro in domains/config.rs

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ffi::events::EventType;
    use serial_test::serial;

    #[test]
    fn init_is_idempotent() {
        unsafe {
            assert_eq!(keyrx_init(), 0);
            assert_eq!(keyrx_init(), 0);
        }
    }

    #[test]
    fn version_matches_package_version() {
        let version = unsafe { CStr::from_ptr(keyrx_version()) }
            .to_str()
            .expect("version string should be valid UTF-8");

        assert_eq!(version, env!("CARGO_PKG_VERSION"));
    }

    #[test]
    fn free_string_handles_null_pointer() {
        unsafe {
            keyrx_free_string(ptr::null_mut());
        }
    }

    #[test]
    fn register_event_callback_accepts_valid_codes() {
        for code in 0..=15 {
            unsafe {
                assert_eq!(keyrx_register_event_callback(code, None), 0);
            }
        }
    }

    #[test]
    fn register_event_callback_rejects_invalid_codes() {
        unsafe {
            assert_eq!(keyrx_register_event_callback(-1, None), -1);
            assert_eq!(keyrx_register_event_callback(18, None), -1);
            assert_eq!(keyrx_register_event_callback(100, None), -1);
        }
    }

    #[test]
    #[serial]
    fn set_config_root_works() {
        crate::config::clear_config_root();

        let temp = std::env::temp_dir();
        let path = CString::new(temp.to_str().unwrap()).unwrap();
        unsafe {
            assert_eq!(keyrx_set_config_root(path.as_ptr()), 0);
        }
        assert_eq!(crate::config::config_dir(), temp);

        crate::config::clear_config_root();
    }

    #[test]
    fn set_config_root_handles_invalid_input() {
        unsafe {
            assert_eq!(keyrx_set_config_root(ptr::null()), -1);
        }
    }
}
