//! Test harness for Rhai script testing.
//!
//! This module provides test primitives that can be registered with the Rhai
//! runtime to enable writing tests for keyboard remapping scripts:
//!
//! - `simulate_tap(key)`: Simulate a key tap (down + up)
//! - `simulate_hold(key, ms)`: Simulate holding a key for a duration
//! - `assert_output(key)`: Assert that a specific key was output
//! - `assert_mapping(from, to)`: Assert that a key maps to another key

use super::helpers::parse_key_or_error;
use crate::engine::{InputEvent, OutputAction};
use rhai::{Engine, EvalAltResult, Position};
use std::cell::RefCell;
use std::sync::Arc;
use std::sync::Mutex;

// Thread-local storage for test outputs and assertions.
thread_local! {
    static TEST_CONTEXT: RefCell<TestContext> = RefCell::new(TestContext::new());
}

/// Context for a single test execution, tracking outputs and assertions.
#[derive(Debug, Clone, Default)]
pub struct TestContext {
    /// Simulated input events generated by test primitives.
    pub inputs: Vec<InputEvent>,
    /// Output actions captured during test execution.
    pub outputs: Vec<OutputAction>,
    /// Assertion results (name, passed, message).
    pub assertions: Vec<AssertionResult>,
    /// Current timestamp for event generation (microseconds).
    pub current_time_us: u64,
}

/// Result of a single assertion.
#[derive(Debug, Clone)]
pub struct AssertionResult {
    pub name: String,
    pub passed: bool,
    pub message: String,
}

impl TestContext {
    /// Create a new empty test context.
    pub fn new() -> Self {
        Self {
            inputs: Vec::new(),
            outputs: Vec::new(),
            assertions: Vec::new(),
            current_time_us: 0,
        }
    }

    /// Reset the context for a new test.
    pub fn reset(&mut self) {
        self.inputs.clear();
        self.outputs.clear();
        self.assertions.clear();
        self.current_time_us = 0;
    }

    /// Add a simulated input event.
    pub fn add_input(&mut self, event: InputEvent) {
        self.inputs.push(event);
    }

    /// Add an output action (captured from engine processing).
    pub fn add_output(&mut self, action: OutputAction) {
        self.outputs.push(action);
    }

    /// Record an assertion result.
    pub fn add_assertion(&mut self, name: String, passed: bool, message: String) {
        self.assertions.push(AssertionResult {
            name,
            passed,
            message,
        });
    }

    /// Advance the simulated time by the given duration.
    pub fn advance_time(&mut self, microseconds: u64) {
        self.current_time_us = self.current_time_us.saturating_add(microseconds);
    }

    /// Get the current simulated timestamp.
    pub fn current_time(&self) -> u64 {
        self.current_time_us
    }

    /// Check if all assertions passed.
    pub fn all_passed(&self) -> bool {
        self.assertions.iter().all(|a| a.passed)
    }

    /// Get the count of failed assertions.
    pub fn failed_count(&self) -> usize {
        self.assertions.iter().filter(|a| !a.passed).count()
    }
}

/// Test harness that provides Rhai test primitives.
///
/// The harness manages test context and provides functions for simulating
/// keyboard input and asserting expected outputs.
pub struct TestHarness {
    /// Shared output collector for capturing engine outputs.
    output_collector: Arc<Mutex<Vec<OutputAction>>>,
}

impl TestHarness {
    /// Create a new test harness.
    pub fn new() -> Self {
        Self {
            output_collector: Arc::new(Mutex::new(Vec::new())),
        }
    }

    /// Get the shared output collector for engine integration.
    pub fn output_collector(&self) -> Arc<Mutex<Vec<OutputAction>>> {
        Arc::clone(&self.output_collector)
    }

    /// Reset the test context for a new test.
    pub fn reset_context(&self) {
        TEST_CONTEXT.with(|ctx| ctx.borrow_mut().reset());
        if let Ok(mut collector) = self.output_collector.lock() {
            collector.clear();
        }
    }

    /// Get the current test context snapshot.
    pub fn context_snapshot(&self) -> TestContext {
        TEST_CONTEXT.with(|ctx| ctx.borrow().clone())
    }

    /// Sync outputs from the collector to the test context.
    pub fn sync_outputs(&self) {
        if let Ok(collector) = self.output_collector.lock() {
            TEST_CONTEXT.with(|ctx| {
                let mut context = ctx.borrow_mut();
                for output in collector.iter() {
                    context.add_output(output.clone());
                }
            });
        }
    }

    /// Register all test functions with the Rhai engine.
    pub fn register_functions(&self, engine: &mut Engine) {
        let collector = Arc::clone(&self.output_collector);
        register_test_functions(engine, collector);
    }
}

impl Default for TestHarness {
    fn default() -> Self {
        Self::new()
    }
}

/// Register all test primitives with the Rhai engine.
///
/// This adds the following functions:
/// - `simulate_tap(key: String)` - Simulate a key tap
/// - `simulate_hold(key: String, duration_ms: i64)` - Simulate holding a key
/// - `assert_output(key: String)` - Assert a key was in the output
/// - `assert_mapping(from: String, to: String)` - Assert key mapping
/// - `assert_blocked(key: String)` - Assert a key was blocked
/// - `clear_outputs()` - Clear captured outputs for fresh assertions
pub fn register_test_functions(
    engine: &mut Engine,
    output_collector: Arc<Mutex<Vec<OutputAction>>>,
) {
    register_simulate_tap(engine);
    register_simulate_hold(engine);
    register_assert_output(engine, Arc::clone(&output_collector));
    register_assert_mapping(engine);
    register_assert_blocked(engine, Arc::clone(&output_collector));
    register_clear_outputs(engine, output_collector);
    register_get_outputs(engine);
}

fn register_simulate_tap(engine: &mut Engine) {
    engine.register_fn(
        "simulate_tap",
        |key: &str| -> Result<(), Box<EvalAltResult>> {
            let key_code = parse_key_or_error(key, "simulate_tap")?;

            TEST_CONTEXT.with(|ctx| {
                let mut context = ctx.borrow_mut();
                let timestamp = context.current_time();

                // Key down event
                let down_event = InputEvent::key_down(key_code, timestamp);
                context.add_input(down_event);

                // Advance time slightly (typical tap duration ~50ms = 50000µs)
                context.advance_time(50_000);

                // Key up event
                let up_event = InputEvent::key_up(key_code, context.current_time());
                context.add_input(up_event);

                // Small gap between events
                context.advance_time(10_000);
            });

            tracing::debug!(
                service = "keyrx",
                event = "test_simulate_tap",
                component = "test_harness",
                key = key,
                "Simulated key tap"
            );

            Ok(())
        },
    );
}

fn register_simulate_hold(engine: &mut Engine) {
    engine.register_fn(
        "simulate_hold",
        |key: &str, duration_ms: i64| -> Result<(), Box<EvalAltResult>> {
            let key_code = parse_key_or_error(key, "simulate_hold")?;

            if duration_ms < 0 {
                return Err(Box::new(EvalAltResult::ErrorRuntime(
                    format!(
                        "simulate_hold: duration must be non-negative, got {}",
                        duration_ms
                    )
                    .into(),
                    Position::NONE,
                )));
            }

            let duration_us = (duration_ms as u64).saturating_mul(1000);

            TEST_CONTEXT.with(|ctx| {
                let mut context = ctx.borrow_mut();
                let timestamp = context.current_time();

                // Key down event
                let down_event = InputEvent::key_down(key_code, timestamp);
                context.add_input(down_event);

                // Advance time by hold duration
                context.advance_time(duration_us);

                // Key up event
                let up_event = InputEvent::key_up(key_code, context.current_time());
                context.add_input(up_event);

                // Small gap between events
                context.advance_time(10_000);
            });

            tracing::debug!(
                service = "keyrx",
                event = "test_simulate_hold",
                component = "test_harness",
                key = key,
                duration_ms = duration_ms,
                "Simulated key hold"
            );

            Ok(())
        },
    );
}

fn register_assert_output(engine: &mut Engine, collector: Arc<Mutex<Vec<OutputAction>>>) {
    engine.register_fn(
        "assert_output",
        move |key: &str| -> Result<bool, Box<EvalAltResult>> {
            let key_code = parse_key_or_error(key, "assert_output")?;

            let found = if let Ok(outputs) = collector.lock() {
                outputs.iter().any(|action| match action {
                    OutputAction::KeyDown(k) | OutputAction::KeyUp(k) | OutputAction::KeyTap(k) => {
                        *k == key_code
                    }
                    _ => false,
                })
            } else {
                false
            };

            let message = if found {
                format!("Key '{}' found in outputs", key)
            } else {
                format!("Key '{}' NOT found in outputs", key)
            };

            TEST_CONTEXT.with(|ctx| {
                ctx.borrow_mut().add_assertion(
                    format!("assert_output({})", key),
                    found,
                    message.clone(),
                );
            });

            if !found {
                return Err(Box::new(EvalAltResult::ErrorRuntime(
                    message.into(),
                    Position::NONE,
                )));
            }

            Ok(true)
        },
    );
}

fn register_assert_mapping(engine: &mut Engine) {
    engine.register_fn(
        "assert_mapping",
        |from: &str, to: &str| -> Result<bool, Box<EvalAltResult>> {
            let from_key = parse_key_or_error(from, "assert_mapping")?;
            let to_key = parse_key_or_error(to, "assert_mapping")?;

            // Check if the mapping exists by looking at the test context inputs/outputs
            // This is a declarative assertion that will be validated by the test runner
            let found = TEST_CONTEXT.with(|ctx| {
                let context = ctx.borrow();
                // Look for a pattern: input of `from` key followed by output of `to` key
                let has_input = context
                    .inputs
                    .iter()
                    .any(|e| e.key == from_key && e.pressed);
                let has_output = context.outputs.iter().any(|action| match action {
                    OutputAction::KeyDown(k) | OutputAction::KeyTap(k) => *k == to_key,
                    _ => false,
                });
                has_input && has_output
            });

            let message = if found {
                format!("Mapping '{}' -> '{}' verified", from, to)
            } else {
                format!(
                    "Mapping '{}' -> '{}' NOT verified (input not found or output mismatch)",
                    from, to
                )
            };

            TEST_CONTEXT.with(|ctx| {
                ctx.borrow_mut().add_assertion(
                    format!("assert_mapping({}, {})", from, to),
                    found,
                    message.clone(),
                );
            });

            if !found {
                return Err(Box::new(EvalAltResult::ErrorRuntime(
                    message.into(),
                    Position::NONE,
                )));
            }

            Ok(true)
        },
    );
}

fn register_assert_blocked(engine: &mut Engine, collector: Arc<Mutex<Vec<OutputAction>>>) {
    engine.register_fn(
        "assert_blocked",
        move |key: &str| -> Result<bool, Box<EvalAltResult>> {
            let _key_code = parse_key_or_error(key, "assert_blocked")?;

            let has_block = if let Ok(outputs) = collector.lock() {
                outputs
                    .iter()
                    .any(|action| matches!(action, OutputAction::Block))
            } else {
                false
            };

            let message = if has_block {
                format!("Key '{}' was blocked", key)
            } else {
                format!("Key '{}' was NOT blocked", key)
            };

            TEST_CONTEXT.with(|ctx| {
                ctx.borrow_mut().add_assertion(
                    format!("assert_blocked({})", key),
                    has_block,
                    message.clone(),
                );
            });

            if !has_block {
                return Err(Box::new(EvalAltResult::ErrorRuntime(
                    message.into(),
                    Position::NONE,
                )));
            }

            Ok(true)
        },
    );
}

fn register_clear_outputs(engine: &mut Engine, collector: Arc<Mutex<Vec<OutputAction>>>) {
    engine.register_fn("clear_outputs", move || {
        if let Ok(mut outputs) = collector.lock() {
            outputs.clear();
        }
        TEST_CONTEXT.with(|ctx| {
            ctx.borrow_mut().outputs.clear();
        });
    });
}

fn register_get_outputs(engine: &mut Engine) {
    engine.register_fn("get_output_count", || -> i64 {
        TEST_CONTEXT.with(|ctx| ctx.borrow().outputs.len() as i64)
    });
}

/// Reset the thread-local test context.
///
/// Call this before each test to ensure a clean state.
pub fn reset_test_context() {
    TEST_CONTEXT.with(|ctx| ctx.borrow_mut().reset());
}

/// Get a snapshot of the current test context.
pub fn get_test_context() -> TestContext {
    TEST_CONTEXT.with(|ctx| ctx.borrow().clone())
}

/// Get the pending input events from the test context.
pub fn get_pending_inputs() -> Vec<InputEvent> {
    TEST_CONTEXT.with(|ctx| ctx.borrow().inputs.clone())
}

/// Add an output action to the test context (for engine integration).
pub fn record_output(action: OutputAction) {
    TEST_CONTEXT.with(|ctx| ctx.borrow_mut().add_output(action));
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::KeyCode;

    #[test]
    fn test_context_reset() {
        reset_test_context();
        let ctx = get_test_context();
        assert!(ctx.inputs.is_empty());
        assert!(ctx.outputs.is_empty());
        assert!(ctx.assertions.is_empty());
        assert_eq!(ctx.current_time_us, 0);
    }

    #[test]
    fn test_context_advance_time() {
        reset_test_context();
        TEST_CONTEXT.with(|ctx| {
            let mut context = ctx.borrow_mut();
            assert_eq!(context.current_time(), 0);
            context.advance_time(1000);
            assert_eq!(context.current_time(), 1000);
            context.advance_time(500);
            assert_eq!(context.current_time(), 1500);
        });
    }

    #[test]
    fn test_harness_creation() {
        let harness = TestHarness::new();
        let collector = harness.output_collector();
        assert!(collector.lock().unwrap().is_empty());
    }

    #[test]
    fn test_harness_reset_context() {
        let harness = TestHarness::new();

        // Add some data
        TEST_CONTEXT.with(|ctx| {
            ctx.borrow_mut()
                .add_input(InputEvent::key_down(KeyCode::A, 0));
        });

        // Reset
        harness.reset_context();

        // Verify cleared
        let ctx = harness.context_snapshot();
        assert!(ctx.inputs.is_empty());
    }

    #[test]
    fn simulate_tap_creates_down_up_events() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        // Execute simulate_tap
        engine.run(r#"simulate_tap("A");"#).unwrap();

        let ctx = get_test_context();
        assert_eq!(ctx.inputs.len(), 2);
        assert!(ctx.inputs[0].pressed); // Key down
        assert!(!ctx.inputs[1].pressed); // Key up
        assert_eq!(ctx.inputs[0].key, KeyCode::A);
        assert_eq!(ctx.inputs[1].key, KeyCode::A);
    }

    #[test]
    fn simulate_hold_respects_duration() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        engine.run(r#"simulate_hold("Space", 200);"#).unwrap();

        let ctx = get_test_context();
        assert_eq!(ctx.inputs.len(), 2);

        let down_time = ctx.inputs[0].timestamp_us;
        let up_time = ctx.inputs[1].timestamp_us;

        // Hold duration should be 200ms = 200,000µs
        assert_eq!(up_time - down_time, 200_000);
    }

    #[test]
    fn simulate_hold_rejects_negative_duration() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        let result = engine.run(r#"simulate_hold("A", -100);"#);
        assert!(result.is_err());
    }

    #[test]
    fn assert_output_fails_when_key_not_found() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        let result = engine.run(r#"assert_output("B");"#);
        assert!(result.is_err());

        let ctx = get_test_context();
        assert_eq!(ctx.assertions.len(), 1);
        assert!(!ctx.assertions[0].passed);
    }

    #[test]
    fn assert_output_succeeds_when_key_found() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        // Add an output to the collector
        let collector = harness.output_collector();
        {
            let mut guard = collector.lock().unwrap();
            guard.push(OutputAction::KeyDown(KeyCode::B));
        }

        let result = engine.run(r#"assert_output("B");"#);
        assert!(result.is_ok());

        let ctx = get_test_context();
        assert_eq!(ctx.assertions.len(), 1);
        assert!(ctx.assertions[0].passed);
    }

    #[test]
    fn clear_outputs_clears_collector() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        // Add outputs
        let collector = harness.output_collector();
        {
            let mut guard = collector.lock().unwrap();
            guard.push(OutputAction::KeyDown(KeyCode::A));
        }

        engine.run("clear_outputs();").unwrap();

        assert!(collector.lock().unwrap().is_empty());
    }

    #[test]
    fn record_output_adds_to_context() {
        reset_test_context();
        record_output(OutputAction::KeyDown(KeyCode::A));
        record_output(OutputAction::KeyUp(KeyCode::A));

        let ctx = get_test_context();
        assert_eq!(ctx.outputs.len(), 2);
    }

    #[test]
    fn all_passed_returns_correct_result() {
        reset_test_context();
        TEST_CONTEXT.with(|ctx| {
            let mut context = ctx.borrow_mut();
            context.add_assertion("test1".into(), true, "passed".into());
            context.add_assertion("test2".into(), true, "passed".into());
            assert!(context.all_passed());

            context.add_assertion("test3".into(), false, "failed".into());
            assert!(!context.all_passed());
            assert_eq!(context.failed_count(), 1);
        });
    }

    #[test]
    fn assert_blocked_fails_when_no_block() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        let result = engine.run(r#"assert_blocked("A");"#);
        assert!(result.is_err());

        let ctx = get_test_context();
        assert_eq!(ctx.assertions.len(), 1);
        assert!(!ctx.assertions[0].passed);
    }

    #[test]
    fn assert_blocked_succeeds_when_block_present() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        // Add a block output to the collector
        let collector = harness.output_collector();
        {
            let mut guard = collector.lock().unwrap();
            guard.push(OutputAction::Block);
        }

        let result = engine.run(r#"assert_blocked("A");"#);
        assert!(result.is_ok());

        let ctx = get_test_context();
        assert_eq!(ctx.assertions.len(), 1);
        assert!(ctx.assertions[0].passed);
    }

    #[test]
    fn get_pending_inputs_returns_inputs() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        engine.run(r#"simulate_tap("A");"#).unwrap();

        let inputs = get_pending_inputs();
        assert_eq!(inputs.len(), 2);
        assert_eq!(inputs[0].key, KeyCode::A);
        assert!(inputs[0].pressed);
        assert_eq!(inputs[1].key, KeyCode::A);
        assert!(!inputs[1].pressed);
    }

    #[test]
    fn sync_outputs_copies_from_collector_to_context() {
        reset_test_context();
        let harness = TestHarness::new();

        // Add outputs to collector
        let collector = harness.output_collector();
        {
            let mut guard = collector.lock().unwrap();
            guard.push(OutputAction::KeyDown(KeyCode::B));
            guard.push(OutputAction::KeyUp(KeyCode::B));
        }

        // Before sync, context outputs are empty
        let ctx_before = get_test_context();
        assert!(ctx_before.outputs.is_empty());

        // Sync outputs
        harness.sync_outputs();

        // After sync, context has the outputs
        let ctx_after = get_test_context();
        assert_eq!(ctx_after.outputs.len(), 2);
    }

    #[test]
    fn simulate_tap_with_invalid_key_returns_error() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        let result = engine.run(r#"simulate_tap("InvalidKeyName");"#);
        assert!(result.is_err());
    }

    #[test]
    fn simulate_hold_with_invalid_key_returns_error() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        let result = engine.run(r#"simulate_hold("InvalidKeyName", 100);"#);
        assert!(result.is_err());
    }

    #[test]
    fn get_output_count_returns_context_output_length() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        // Add some outputs to context
        record_output(OutputAction::KeyDown(KeyCode::A));
        record_output(OutputAction::KeyUp(KeyCode::A));

        let result: i64 = engine.eval("get_output_count()").unwrap();
        assert_eq!(result, 2);
    }

    #[test]
    fn test_context_default_is_empty() {
        let ctx = TestContext::default();
        assert!(ctx.inputs.is_empty());
        assert!(ctx.outputs.is_empty());
        assert!(ctx.assertions.is_empty());
        assert_eq!(ctx.current_time_us, 0);
    }

    #[test]
    fn assert_mapping_records_assertion() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        // First simulate a tap to add input
        engine.run(r#"simulate_tap("A");"#).unwrap();

        // Add output to context
        record_output(OutputAction::KeyDown(KeyCode::B));

        // This should fail because we're checking mapping from A to B
        // but the assertion logic checks both input and output
        let result = engine.run(r#"assert_mapping("A", "B");"#);

        // The assertion was recorded
        let ctx = get_test_context();
        let mapping_assertion = ctx
            .assertions
            .iter()
            .find(|a| a.name.contains("assert_mapping"));
        assert!(mapping_assertion.is_some());
    }

    #[test]
    fn multiple_simulate_taps_advance_time() {
        reset_test_context();
        let mut engine = Engine::new();
        let harness = TestHarness::new();
        harness.register_functions(&mut engine);

        engine.run(r#"simulate_tap("A");"#).unwrap();
        let time_after_first = get_test_context().current_time_us;

        engine.run(r#"simulate_tap("B");"#).unwrap();
        let time_after_second = get_test_context().current_time_us;

        // Time should have advanced
        assert!(time_after_second > time_after_first);

        // Should have 4 inputs total (2 taps = 4 events)
        let ctx = get_test_context();
        assert_eq!(ctx.inputs.len(), 4);
    }
}
