//! Test harness for Rhai script testing.
//!
//! This module provides test primitives that can be registered with the Rhai
//! runtime to enable writing tests for keyboard remapping scripts:
//!
//! - `simulate_tap(key)`: Simulate a key tap (down + up)
//! - `simulate_hold(key, ms)`: Simulate holding a key for a duration
//! - `assert_output(key)`: Assert that a specific key was output
//! - `assert_mapping(from, to)`: Assert that a key maps to another key

use crate::engine::{InputEvent, OutputAction};
use rhai::Engine;
use std::cell::RefCell;
use std::sync::Arc;
use std::sync::Mutex;

// Import test primitive registration functions from test_primitives module
use super::test_primitives::{
    register_assert_blocked, register_assert_mapping, register_assert_output,
    register_clear_outputs, register_get_outputs, register_simulate_hold, register_simulate_tap,
};

// Thread-local storage for test outputs and assertions.
// This is pub(super) to allow test_primitives to access it.
thread_local! {
    pub(super) static TEST_CONTEXT: RefCell<TestContext> = RefCell::new(TestContext::new());
}

/// Context for a single test execution, tracking outputs and assertions.
#[derive(Debug, Clone, Default)]
pub struct TestContext {
    /// Simulated input events generated by test primitives.
    pub inputs: Vec<InputEvent>,
    /// Output actions captured during test execution.
    pub outputs: Vec<OutputAction>,
    /// Assertion results (name, passed, message).
    pub assertions: Vec<AssertionResult>,
    /// Current timestamp for event generation (microseconds).
    pub current_time_us: u64,
}

/// Result of a single assertion.
#[derive(Debug, Clone)]
pub struct AssertionResult {
    pub name: String,
    pub passed: bool,
    pub message: String,
}

impl TestContext {
    /// Create a new empty test context.
    pub fn new() -> Self {
        Self {
            inputs: Vec::new(),
            outputs: Vec::new(),
            assertions: Vec::new(),
            current_time_us: 0,
        }
    }

    /// Reset the context for a new test.
    pub fn reset(&mut self) {
        self.inputs.clear();
        self.outputs.clear();
        self.assertions.clear();
        self.current_time_us = 0;
    }

    /// Add a simulated input event.
    pub fn add_input(&mut self, event: InputEvent) {
        self.inputs.push(event);
    }

    /// Add an output action (captured from engine processing).
    pub fn add_output(&mut self, action: OutputAction) {
        self.outputs.push(action);
    }

    /// Record an assertion result.
    pub fn add_assertion(&mut self, name: String, passed: bool, message: String) {
        self.assertions.push(AssertionResult {
            name,
            passed,
            message,
        });
    }

    /// Advance the simulated time by the given duration.
    pub fn advance_time(&mut self, microseconds: u64) {
        self.current_time_us = self.current_time_us.saturating_add(microseconds);
    }

    /// Get the current simulated timestamp.
    pub fn current_time(&self) -> u64 {
        self.current_time_us
    }

    /// Check if all assertions passed.
    pub fn all_passed(&self) -> bool {
        self.assertions.iter().all(|a| a.passed)
    }

    /// Get the count of failed assertions.
    pub fn failed_count(&self) -> usize {
        self.assertions.iter().filter(|a| !a.passed).count()
    }
}

/// Test harness that provides Rhai test primitives.
///
/// The harness manages test context and provides functions for simulating
/// keyboard input and asserting expected outputs.
pub struct TestHarness {
    /// Shared output collector for capturing engine outputs.
    output_collector: Arc<Mutex<Vec<OutputAction>>>,
}

impl TestHarness {
    /// Create a new test harness.
    pub fn new() -> Self {
        Self {
            output_collector: Arc::new(Mutex::new(Vec::new())),
        }
    }

    /// Get the shared output collector for engine integration.
    pub fn output_collector(&self) -> Arc<Mutex<Vec<OutputAction>>> {
        Arc::clone(&self.output_collector)
    }

    /// Reset the test context for a new test.
    pub fn reset_context(&self) {
        TEST_CONTEXT.with(|ctx| ctx.borrow_mut().reset());
        if let Ok(mut collector) = self.output_collector.lock() {
            collector.clear();
        }
    }

    /// Get the current test context snapshot.
    pub fn context_snapshot(&self) -> TestContext {
        TEST_CONTEXT.with(|ctx| ctx.borrow().clone())
    }

    /// Sync outputs from the collector to the test context.
    pub fn sync_outputs(&self) {
        if let Ok(collector) = self.output_collector.lock() {
            TEST_CONTEXT.with(|ctx| {
                let mut context = ctx.borrow_mut();
                for output in collector.iter() {
                    context.add_output(output.clone());
                }
            });
        }
    }

    /// Register all test functions with the Rhai engine.
    pub fn register_functions(&self, engine: &mut Engine) {
        let collector = Arc::clone(&self.output_collector);
        register_test_functions(engine, collector);
    }
}

impl Default for TestHarness {
    fn default() -> Self {
        Self::new()
    }
}

/// Register all test primitives with the Rhai engine.
///
/// This adds the following functions:
/// - `simulate_tap(key: String)` - Simulate a key tap
/// - `simulate_hold(key: String, duration_ms: i64)` - Simulate holding a key
/// - `assert_output(key: String)` - Assert a key was in the output
/// - `assert_mapping(from: String, to: String)` - Assert key mapping
/// - `assert_blocked(key: String)` - Assert a key was blocked
/// - `clear_outputs()` - Clear captured outputs for fresh assertions
pub fn register_test_functions(
    engine: &mut Engine,
    output_collector: Arc<Mutex<Vec<OutputAction>>>,
) {
    register_simulate_tap(engine);
    register_simulate_hold(engine);
    register_assert_output(engine, Arc::clone(&output_collector));
    register_assert_mapping(engine);
    register_assert_blocked(engine, Arc::clone(&output_collector));
    register_clear_outputs(engine, output_collector);
    register_get_outputs(engine);
}

/// Reset the thread-local test context.
///
/// Call this before each test to ensure a clean state.
pub fn reset_test_context() {
    TEST_CONTEXT.with(|ctx| ctx.borrow_mut().reset());
}

/// Get a snapshot of the current test context.
pub fn get_test_context() -> TestContext {
    TEST_CONTEXT.with(|ctx| ctx.borrow().clone())
}

/// Get the pending input events from the test context.
pub fn get_pending_inputs() -> Vec<InputEvent> {
    TEST_CONTEXT.with(|ctx| ctx.borrow().inputs.clone())
}

/// Add an output action to the test context (for engine integration).
pub fn record_output(action: OutputAction) {
    TEST_CONTEXT.with(|ctx| ctx.borrow_mut().add_output(action));
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::KeyCode;

    #[test]
    fn test_context_reset() {
        reset_test_context();
        let ctx = get_test_context();
        assert!(ctx.inputs.is_empty());
        assert!(ctx.outputs.is_empty());
        assert!(ctx.assertions.is_empty());
        assert_eq!(ctx.current_time_us, 0);
    }

    #[test]
    fn test_context_advance_time() {
        reset_test_context();
        TEST_CONTEXT.with(|ctx| {
            let mut context = ctx.borrow_mut();
            assert_eq!(context.current_time(), 0);
            context.advance_time(1000);
            assert_eq!(context.current_time(), 1000);
            context.advance_time(500);
            assert_eq!(context.current_time(), 1500);
        });
    }

    #[test]
    fn test_harness_creation() {
        let harness = TestHarness::new();
        let collector = harness.output_collector();
        assert!(collector.lock().unwrap().is_empty());
    }

    #[test]
    fn test_harness_reset_context() {
        let harness = TestHarness::new();

        // Add some data
        TEST_CONTEXT.with(|ctx| {
            ctx.borrow_mut()
                .add_input(InputEvent::key_down(KeyCode::A, 0));
        });

        // Reset
        harness.reset_context();

        // Verify cleared
        let ctx = harness.context_snapshot();
        assert!(ctx.inputs.is_empty());
    }

    #[test]
    fn record_output_adds_to_context() {
        reset_test_context();
        record_output(OutputAction::KeyDown(KeyCode::A));
        record_output(OutputAction::KeyUp(KeyCode::A));

        let ctx = get_test_context();
        assert_eq!(ctx.outputs.len(), 2);
    }

    #[test]
    fn all_passed_returns_correct_result() {
        reset_test_context();
        TEST_CONTEXT.with(|ctx| {
            let mut context = ctx.borrow_mut();
            context.add_assertion("test1".into(), true, "passed".into());
            context.add_assertion("test2".into(), true, "passed".into());
            assert!(context.all_passed());

            context.add_assertion("test3".into(), false, "failed".into());
            assert!(!context.all_passed());
            assert_eq!(context.failed_count(), 1);
        });
    }

    #[test]
    fn get_pending_inputs_returns_inputs() {
        reset_test_context();
        TEST_CONTEXT.with(|ctx| {
            let mut context = ctx.borrow_mut();
            context.add_input(InputEvent::key_down(KeyCode::A, 0));
            context.add_input(InputEvent::key_up(KeyCode::A, 50000));
        });

        let inputs = get_pending_inputs();
        assert_eq!(inputs.len(), 2);
        assert_eq!(inputs[0].key, KeyCode::A);
        assert!(inputs[0].pressed);
        assert_eq!(inputs[1].key, KeyCode::A);
        assert!(!inputs[1].pressed);
    }

    #[test]
    fn sync_outputs_copies_from_collector_to_context() {
        reset_test_context();
        let harness = TestHarness::new();

        // Add outputs to collector
        let collector = harness.output_collector();
        {
            let mut guard = collector.lock().unwrap();
            guard.push(OutputAction::KeyDown(KeyCode::B));
            guard.push(OutputAction::KeyUp(KeyCode::B));
        }

        // Before sync, context outputs are empty
        let ctx_before = get_test_context();
        assert!(ctx_before.outputs.is_empty());

        // Sync outputs
        harness.sync_outputs();

        // After sync, context has the outputs
        let ctx_after = get_test_context();
        assert_eq!(ctx_after.outputs.len(), 2);
    }

    #[test]
    fn test_context_default_is_empty() {
        let ctx = TestContext::default();
        assert!(ctx.inputs.is_empty());
        assert!(ctx.outputs.is_empty());
        assert!(ctx.assertions.is_empty());
        assert_eq!(ctx.current_time_us, 0);
    }
}
