// GENERATED CODE - DO NOT EDIT
// This file was generated by the Dart binding generator.
// Generation time: 2025-12-11T14:52:47Z
// Source contracts: core/src/ffi/contracts/*.ffi-contract.json
//
// To regenerate: cargo run --bin generate-dart-bindings
// Or: just gen-dart-bindings

// ignore_for_file: non_constant_identifier_names
