// Auto-generated by scripts/generate-version.js - DO NOT EDIT
// Generated at: 2026-03-15T05:14:53.165Z
// Source: package.json v1.0.0

export const VERSION = '1.0.0';
export const BUILD_TIME = '2026-03-15T05:14:53.165Z';
export const GIT_COMMIT = '97c0ed2f-dirty';
export const GIT_BRANCH = 'main';

// Build info object
export const BUILD_INFO = {
  version: VERSION,
  buildTime: BUILD_TIME,
  gitCommit: GIT_COMMIT,
  gitBranch: GIT_BRANCH,
  gitDirty: true,
} as const;
