// Auto-generated by scripts/generate-version.js - DO NOT EDIT
// Generated at: 2026-01-27T23:07:41.618Z
// Source: package.json v0.1.1

export const VERSION = '0.1.1';
export const BUILD_TIME = '2026-01-27T23:07:41.618Z';
export const GIT_COMMIT = '2a428f19-dirty';
export const GIT_BRANCH = 'main';

// Build info object
export const BUILD_INFO = {
  version: VERSION,
  buildTime: BUILD_TIME,
  gitCommit: GIT_COMMIT,
  gitBranch: GIT_BRANCH,
  gitDirty: true,
} as const;
