// Auto-generated by scripts/generate-version.js - DO NOT EDIT
// Generated at: 2026-01-29T12:50:35.353Z
// Source: package.json v0.1.5

export const VERSION = '0.1.5';
export const BUILD_TIME = '2026-01-29T12:50:35.353Z';
export const GIT_COMMIT = 'e427a955-dirty';
export const GIT_BRANCH = 'main';

// Build info object
export const BUILD_INFO = {
  version: VERSION,
  buildTime: BUILD_TIME,
  gitCommit: GIT_COMMIT,
  gitBranch: GIT_BRANCH,
  gitDirty: true,
} as const;
