//! CLI command implementations.

mod analyze;
mod bench;
mod check;
mod ci_check;
mod devices;
mod discover;
mod discover_session;
mod discover_validation;
mod docs;
mod doctor;
mod exit_codes;
mod golden;
mod migrate;
mod regression;
mod repl;
mod replay;
mod run;
mod run_builder;
mod run_recorder;
mod run_tracer;
mod simulate;
mod state;
mod test;
mod uat;

pub use analyze::{AnalysisResult, AnalyzeCommand};
pub use bench::BenchCommand;
pub use check::CheckCommand;
pub use ci_check::{exit_codes as ci_check_exit_codes, CiCheckCommand, CiCheckSummary};
pub use devices::{DeviceAction, DevicesCommand};
pub use discover::{DiscoverCommand, DiscoverExit};
pub use docs::{DocFormat, DocsCommand};
pub use doctor::{CheckStatus, DiagnosticCheck, DoctorCommand};
pub use exit_codes::ExitCodesCommand;
pub use golden::{exit_codes as golden_exit_codes, GoldenCommand, GoldenSubcommand};
pub use migrate::MigrateCommand;
pub use regression::{exit_codes as regression_exit_codes, RegressionCommand, RegressionSummary};
pub use repl::ReplCommand;
pub use replay::{exit_codes as replay_exit_codes, ReplayCommand, VerificationResult};
pub use run::RunCommand;
pub use simulate::{SimulateCommand, SimulationOutput, SimulationResult, TapHoldInfo};
pub use state::StateCommand;
pub use test::{exit_codes as test_exit_codes, TestCommand};
pub use uat::{exit_codes as uat_exit_codes, UatCommand};
