/**
 * Unit tests for Rhai code generator
 */

import { describe, it, expect } from 'vitest';
import { generateRhaiCode } from './rhaiGenerator';
import { ConfigState, Layer, Modifier, Lock, Mapping } from '../types/configBuilder';

describe('rhaiGenerator', () => {
  describe('generateRhaiCode', () => {
    it('should generate empty configuration with device block', () => {
      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [],
        modifiers: [],
        locks: [],
      };

      const result = generateRhaiCode(config);

      expect(result).toContain('device_start("*");');
      expect(result).toContain('device_end();');
    });

    it('should generate configuration with header comments', () => {
      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [],
        modifiers: [],
        locks: [],
      };

      const result = generateRhaiCode(config, { includeComments: true });

      expect(result).toContain('// KeyRx2 Configuration');
      expect(result).toContain('// Generated by Visual Config Builder');
      expect(result).toContain('// Prefix system:');
      expect(result).toContain('//   VK_ = Virtual Key');
      expect(result).toContain('//   MD_ = Custom Modifier');
      expect(result).toContain('//   LK_ = Custom Lock');
    });

    it('should generate configuration without comments when disabled', () => {
      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [],
        modifiers: [],
        locks: [],
      };

      const result = generateRhaiCode(config, { includeComments: false });

      expect(result).not.toContain('// KeyRx2 Configuration');
      expect(result).toContain('device_start("*");');
      expect(result).toContain('device_end();');
    });

    it('should generate simple key mappings with VK_ prefix', () => {
      const mapping: Mapping = {
        id: 'm1',
        sourceKey: 'A',
        targetKey: 'B',
        type: 'simple',
      };

      const baseLayer: Layer = {
        id: 'base',
        name: 'base',
        mappings: [mapping],
        isBase: true,
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [baseLayer],
        modifiers: [],
        locks: [],
      };

      const result = generateRhaiCode(config);

      expect(result).toContain('map("A", "VK_B")');
    });

    it('should normalize KEY_ prefix from source keys', () => {
      const mapping: Mapping = {
        id: 'm1',
        sourceKey: 'KEY_Q',
        targetKey: 'KEY_A',
        type: 'simple',
      };

      const baseLayer: Layer = {
        id: 'base',
        name: 'base',
        mappings: [mapping],
        isBase: true,
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [baseLayer],
        modifiers: [],
        locks: [],
      };

      const result = generateRhaiCode(config);

      expect(result).toContain('map("Q", "VK_A")');
    });

    it('should generate modifier mappings with MD_XX IDs', () => {
      const modifier: Modifier = {
        id: 'mod1',
        name: 'nav_layer',
        triggerKey: 'CapsLock',
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [],
        modifiers: [modifier],
        locks: [],
      };

      const result = generateRhaiCode(config);

      expect(result).toContain('// Custom Modifiers');
      expect(result).toContain('map("CapsLock", "MD_00");');
    });

    it('should generate multiple modifiers with sequential IDs', () => {
      const modifiers: Modifier[] = [
        { id: 'mod1', name: 'nav_layer', triggerKey: 'CapsLock' },
        { id: 'mod2', name: 'num_layer', triggerKey: 'Space' },
        { id: 'mod3', name: 'fn_layer', triggerKey: 'Tab' },
      ];

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [],
        modifiers,
        locks: [],
      };

      const result = generateRhaiCode(config);

      expect(result).toContain('map("CapsLock", "MD_00");');
      expect(result).toContain('map("Space", "MD_01");');
      expect(result).toContain('map("Tab", "MD_02");');
    });

    it('should generate lock mappings with LK_XX IDs', () => {
      const lock: Lock = {
        id: 'lock1',
        name: 'game_mode',
        triggerKey: 'ScrollLock',
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [],
        modifiers: [],
        locks: [lock],
      };

      const result = generateRhaiCode(config);

      expect(result).toContain('// Custom Locks');
      expect(result).toContain('map("ScrollLock", "LK_00");');
    });

    it('should generate base layer mappings without when() wrapper', () => {
      const mappings: Mapping[] = [
        { id: 'm1', sourceKey: 'A', targetKey: 'B', type: 'simple' },
        { id: 'm2', sourceKey: 'Q', targetKey: 'W', type: 'simple' },
      ];

      const baseLayer: Layer = {
        id: 'base',
        name: 'base',
        mappings,
        isBase: true,
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [baseLayer],
        modifiers: [],
        locks: [],
      };

      const result = generateRhaiCode(config);

      expect(result).toContain('// Base Layer Mappings');
      expect(result).toContain('map("A", "VK_B")');
      expect(result).toContain('map("Q", "VK_W")');
      expect(result).not.toContain('when(');
    });

    it('should generate conditional layers with when() blocks', () => {
      const baseLayer: Layer = {
        id: 'base',
        name: 'base',
        mappings: [],
        isBase: true,
      };

      const navLayer: Layer = {
        id: 'nav',
        name: 'Navigation',
        mappings: [
          { id: 'm1', sourceKey: 'H', targetKey: 'Left', type: 'simple' },
          { id: 'm2', sourceKey: 'J', targetKey: 'Down', type: 'simple' },
          { id: 'm3', sourceKey: 'K', targetKey: 'Up', type: 'simple' },
          { id: 'm4', sourceKey: 'L', targetKey: 'Right', type: 'simple' },
        ],
        isBase: false,
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [baseLayer, navLayer],
        modifiers: [],
        locks: [],
      };

      const result = generateRhaiCode(config);

      expect(result).toContain('// Navigation Layer (active when MD_00 is held)');
      expect(result).toContain('when("MD_00", [');
      expect(result).toContain('map("H", "VK_Left")');
      expect(result).toContain('map("J", "VK_Down")');
      expect(result).toContain('map("K", "VK_Up")');
      expect(result).toContain('map("L", "VK_Right")');
      expect(result).toContain(']);');
    });

    it('should add commas between mappings in when() blocks except last', () => {
      const navLayer: Layer = {
        id: 'nav',
        name: 'Navigation',
        mappings: [
          { id: 'm1', sourceKey: 'H', targetKey: 'Left', type: 'simple' },
          { id: 'm2', sourceKey: 'J', targetKey: 'Down', type: 'simple' },
        ],
        isBase: false,
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [navLayer],
        modifiers: [],
        locks: [],
      };

      const result = generateRhaiCode(config);

      expect(result).toContain('map("H", "VK_Left"),');
      expect(result).toContain('map("J", "VK_Down")');
      expect(result).not.toContain('map("J", "VK_Down"),');
    });

    it('should generate complete configuration with modifiers, locks, and layers', () => {
      const modifier: Modifier = {
        id: 'mod1',
        name: 'nav_layer',
        triggerKey: 'CapsLock',
      };

      const lock: Lock = {
        id: 'lock1',
        name: 'game_mode',
        triggerKey: 'ScrollLock',
      };

      const baseLayer: Layer = {
        id: 'base',
        name: 'base',
        mappings: [
          { id: 'm1', sourceKey: 'A', targetKey: 'B', type: 'simple' },
        ],
        isBase: true,
      };

      const navLayer: Layer = {
        id: 'nav',
        name: 'Navigation',
        mappings: [
          { id: 'm2', sourceKey: 'H', targetKey: 'Left', type: 'simple' },
        ],
        isBase: false,
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [baseLayer, navLayer],
        modifiers: [modifier],
        locks: [lock],
      };

      const result = generateRhaiCode(config);

      // Check structure
      expect(result).toContain('device_start("*");');
      expect(result).toContain('device_end();');

      // Check modifier section
      expect(result).toContain('// Custom Modifiers');
      expect(result).toContain('map("CapsLock", "MD_00");');

      // Check lock section
      expect(result).toContain('// Custom Locks');
      expect(result).toContain('map("ScrollLock", "LK_00");');

      // Check base layer
      expect(result).toContain('// Base Layer Mappings');
      expect(result).toContain('map("A", "VK_B")');

      // Check conditional layer
      expect(result).toContain('// Navigation Layer (active when MD_00 is held)');
      expect(result).toContain('when("MD_00", [');
      expect(result).toContain('map("H", "VK_Left")');
    });

    it('should respect custom indent option', () => {
      const baseLayer: Layer = {
        id: 'base',
        name: 'base',
        mappings: [
          { id: 'm1', sourceKey: 'A', targetKey: 'B', type: 'simple' },
        ],
        isBase: true,
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [baseLayer],
        modifiers: [],
        locks: [],
      };

      const result = generateRhaiCode(config, { indent: '  ' });

      expect(result).toContain('  // Base Layer Mappings');
      expect(result).toContain('  map("A", "VK_B")');
    });

    it('should preserve VK_ prefix if already present', () => {
      const mapping: Mapping = {
        id: 'm1',
        sourceKey: 'A',
        targetKey: 'VK_B',
        type: 'simple',
      };

      const baseLayer: Layer = {
        id: 'base',
        name: 'base',
        mappings: [mapping],
        isBase: true,
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [baseLayer],
        modifiers: [],
        locks: [],
      };

      const result = generateRhaiCode(config);

      expect(result).toContain('map("A", "VK_B")');
      expect(result).not.toContain('VK_VK_B');
    });

    it('should handle empty layers gracefully', () => {
      const baseLayer: Layer = {
        id: 'base',
        name: 'base',
        mappings: [],
        isBase: true,
      };

      const navLayer: Layer = {
        id: 'nav',
        name: 'Navigation',
        mappings: [],
        isBase: false,
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [baseLayer, navLayer],
        modifiers: [],
        locks: [],
      };

      const result = generateRhaiCode(config);

      expect(result).toContain('device_start("*");');
      expect(result).toContain('device_end();');
      // Empty nav layer should not generate when() block
      expect(result).not.toContain('when("MD_00"');
    });

    it('should generate valid Rhai for CapsLock to Escape mapping', () => {
      const mapping: Mapping = {
        id: 'm1',
        sourceKey: 'CapsLock',
        targetKey: 'Escape',
        type: 'simple',
      };

      const baseLayer: Layer = {
        id: 'base',
        name: 'base',
        mappings: [mapping],
        isBase: true,
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [baseLayer],
        modifiers: [],
        locks: [],
      };

      const result = generateRhaiCode(config);

      expect(result).toContain('map("CapsLock", "VK_Escape")');
    });

    it('should generate modifier_trigger mappings correctly', () => {
      const modifier: Modifier = {
        id: 'mod1',
        name: 'nav_layer',
        triggerKey: 'CapsLock',
      };

      const mapping: Mapping = {
        id: 'm1',
        sourceKey: 'Space',
        targetKey: 'Space',
        type: 'modifier_trigger',
        modifierId: 'mod1',
      };

      const baseLayer: Layer = {
        id: 'base',
        name: 'base',
        mappings: [mapping],
        isBase: true,
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [baseLayer],
        modifiers: [modifier],
        locks: [],
      };

      const result = generateRhaiCode(config);

      // Should map to MD_00 (first modifier)
      expect(result).toContain('map("Space", "MD_00")');
    });

    it('should disable pretty formatting when pretty option is false', () => {
      const modifier: Modifier = {
        id: 'mod1',
        name: 'nav_layer',
        triggerKey: 'CapsLock',
      };

      const config: Pick<ConfigState, 'layers' | 'modifiers' | 'locks'> = {
        layers: [],
        modifiers: [modifier],
        locks: [],
      };

      const resultPretty = generateRhaiCode(config, { pretty: true });
      const resultCompact = generateRhaiCode(config, { pretty: false });

      // Pretty version should have more newlines
      expect(resultPretty.split('\n').length).toBeGreaterThan(resultCompact.split('\n').length);
    });
  });
});
