//! FFI Runtime Library for KeyRx
//!
//! This crate provides runtime helpers for FFI code generated by the `keyrx_ffi_macro` crate.
//! It includes utilities for:
//!
//! - C string parsing and conversion
//! - JSON serialization to C strings
//! - Panic catching at FFI boundaries
//! - Complete FFI wrapper functions
//!
//! # Safety
//!
//! All functions that interact with raw pointers are marked `unsafe` and require
//! callers to ensure pointer validity.

#![deny(unsafe_op_in_unsafe_fn)]
// FFI code requires unsafe - this is intentional and reviewed
#![allow(unsafe_code)]

pub mod json;
pub mod panic;
pub mod string;
pub mod wrapper;

// Re-export commonly used items at the crate root
pub use json::serialize_to_c_string;
pub use panic::handle_panic;
pub use string::parse_c_string;
pub use wrapper::ffi_wrapper;

#[cfg(test)]
mod tests;
