#!/usr/bin/env python3
"""
Benchmark regression checker for Criterion benchmark results.

Parses Criterion's JSON output files and compares against baseline to detect
performance regressions exceeding the specified threshold.

Exit codes:
    0: All benchmarks within threshold
    1: At least one benchmark exceeded threshold (regression detected)
    2: Error processing benchmark data
"""

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass
class BenchmarkResult:
    """A single benchmark result with timing data."""

    name: str
    baseline_ns: float
    current_ns: float
    delta_ns: float
    delta_percent: float

    @property
    def delta_us(self) -> float:
        """Return delta in microseconds."""
        return self.delta_ns / 1000.0

    @property
    def baseline_us(self) -> float:
        """Return baseline in microseconds."""
        return self.baseline_ns / 1000.0

    @property
    def current_us(self) -> float:
        """Return current in microseconds."""
        return self.current_ns / 1000.0


def parse_criterion_estimates(estimates_path: Path) -> float | None:
    """Parse Criterion estimates.json and return mean time in nanoseconds."""
    if not estimates_path.exists():
        return None

    try:
        with open(estimates_path, encoding="utf-8") as f:
            data = json.load(f)
        return data.get("mean", {}).get("point_estimate")
    except (json.JSONDecodeError, KeyError, TypeError):
        return None


def find_benchmarks(
    criterion_dir: Path, baseline_name: str, current_name: str
) -> list[str]:
    """Find all benchmark names in the Criterion directory."""
    benchmarks = []
    if not criterion_dir.exists():
        return benchmarks

    for bench_dir in criterion_dir.iterdir():
        if bench_dir.is_dir() and bench_dir.name not in ("report", ".history"):
            # Check if this is a benchmark directory (has estimates.json for either run)
            has_baseline = (bench_dir / baseline_name / "estimates.json").exists()
            has_current = (bench_dir / current_name / "estimates.json").exists()
            has_new = (bench_dir / "new" / "estimates.json").exists()
            if has_baseline and (has_current or has_new):
                benchmarks.append(bench_dir.name)

    return sorted(benchmarks)


def compare_benchmarks(
    criterion_dir: Path, baseline_name: str = "main", current_name: str = "pr"
) -> list[BenchmarkResult]:
    """Compare baseline and current benchmark results."""
    results = []
    benchmarks = find_benchmarks(criterion_dir, baseline_name, current_name)

    for bench_name in benchmarks:
        bench_dir = criterion_dir / bench_name

        baseline_path = bench_dir / baseline_name / "estimates.json"
        current_path = bench_dir / current_name / "estimates.json"

        # Fall back to "new" if "pr" doesn't exist (local runs)
        if not current_path.exists():
            current_path = bench_dir / "new" / "estimates.json"

        baseline_ns = parse_criterion_estimates(baseline_path)
        current_ns = parse_criterion_estimates(current_path)

        if baseline_ns is None or current_ns is None:
            continue

        delta_ns = current_ns - baseline_ns
        delta_percent = (delta_ns / baseline_ns) * 100 if baseline_ns > 0 else 0

        results.append(
            BenchmarkResult(
                name=bench_name,
                baseline_ns=baseline_ns,
                current_ns=current_ns,
                delta_ns=delta_ns,
                delta_percent=delta_percent,
            )
        )

    return results


def generate_report(
    results: list[BenchmarkResult], threshold_us: float, has_regression: bool
) -> str:
    """Generate a markdown report of benchmark results."""
    lines = ["## 📊 Benchmark Results\n"]

    if has_regression:
        lines.append(
            f"⚠️ **Performance regression detected!** "
            f"Threshold: {threshold_us}µs\n"
        )
    else:
        lines.append("✅ All benchmarks within acceptable range.\n")

    lines.append("\n| Benchmark | Baseline | Current | Delta | Status |")
    lines.append("|-----------|----------|---------|-------|--------|")

    for result in results:
        status = "🔴 REGRESSION" if result.delta_us > threshold_us else "✅ OK"
        if result.delta_us < -threshold_us:
            status = "🚀 IMPROVED"

        lines.append(
            f"| {result.name} | "
            f"{result.baseline_us:.2f}µs | "
            f"{result.current_us:.2f}µs | "
            f"{result.delta_us:+.2f}µs ({result.delta_percent:+.1f}%) | "
            f"{status} |"
        )

    lines.append("\n---")
    lines.append(
        f"*Threshold: {threshold_us}µs | "
        f"Generated by check_bench_regression.py*"
    )

    return "\n".join(lines)


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Check Criterion benchmarks for performance regressions"
    )
    parser.add_argument(
        "--baseline-dir",
        type=Path,
        required=True,
        help="Path to Criterion benchmark directory (e.g., core/target/criterion)",
    )
    parser.add_argument(
        "--threshold-us",
        type=float,
        default=100.0,
        help="Regression threshold in microseconds (default: 100)",
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=None,
        help="Output path for markdown report",
    )
    parser.add_argument(
        "--baseline-name",
        default="main",
        help="Name of baseline benchmark run (default: main)",
    )
    parser.add_argument(
        "--current-name",
        default="pr",
        help="Name of current benchmark run (default: pr)",
    )

    args = parser.parse_args()

    if not args.baseline_dir.exists():
        print(f"Error: Criterion directory not found: {args.baseline_dir}")
        return 2

    results = compare_benchmarks(
        args.baseline_dir, args.baseline_name, args.current_name
    )

    if not results:
        print("Warning: No benchmark results found to compare")
        report = "## 📊 Benchmark Results\n\n⚠️ No benchmark data found.\n"
        if args.report:
            args.report.write_text(report)
        return 0

    has_regression = any(r.delta_us > args.threshold_us for r in results)
    report = generate_report(results, args.threshold_us, has_regression)

    print(report)

    if args.report:
        args.report.write_text(report)
        print(f"\nReport written to: {args.report}")

    if has_regression:
        print(f"\n❌ FAILED: Regression exceeds {args.threshold_us}µs threshold")
        return 1

    print(f"\n✅ PASSED: All benchmarks within {args.threshold_us}µs threshold")
    return 0


if __name__ == "__main__":
    sys.exit(main())
