#!/usr/bin/env python3
"""
Verify that Dart FFI bindings are in sync with Rust exports.

This script checks if the generated bindings match what would be generated
from the current Rust FFI exports. Useful for CI/CD to catch binding drift.

Exit codes:
    0 - Bindings are in sync
    1 - Bindings are out of sync or error occurred
"""

import sys
import tempfile
from pathlib import Path
import subprocess


def main():
    """Main verification routine."""
    # Determine project root
    script_dir = Path(__file__).parent
    project_root = script_dir.parent

    print("KeyRX Bindings Verification")
    print("=" * 60)
    print(f"Project root: {project_root}")

    # Path to existing generated bindings
    existing_bindings = project_root / 'ui' / 'lib' / 'ffi' / 'generated' / 'bindings_generated.dart'

    if not existing_bindings.exists():
        print("ERROR: Generated bindings file not found!")
        print(f"Expected: {existing_bindings}")
        print("\nRun: just gen-bindings")
        return 1

    # Read existing bindings
    print(f"\nReading existing bindings: {existing_bindings.relative_to(project_root)}")
    existing_content = existing_bindings.read_text(encoding='utf-8')

    # Generate fresh bindings to temp file
    print("Generating fresh bindings for comparison...")
    with tempfile.TemporaryDirectory() as tmpdir:
        # Run the generator script
        generator_script = project_root / 'scripts' / 'generate_dart_bindings.py'

        # We'll temporarily modify the generator to output to temp directory
        # For simplicity, we'll just run it and compare outputs
        try:
            # Run generator and capture what it would generate
            result = subprocess.run(
                [sys.executable, str(generator_script)],
                cwd=project_root,
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode != 0:
                print("ERROR: Binding generation failed!")
                print(result.stderr)
                return 1

            # Read the newly generated file
            fresh_content = existing_bindings.read_text(encoding='utf-8')

        except subprocess.TimeoutExpired:
            print("ERROR: Binding generation timed out!")
            return 1
        except Exception as e:
            print(f"ERROR: Failed to generate bindings: {e}")
            return 1

    # Compare the contents (ignoring timestamp differences in comments)
    if normalize_bindings(existing_content) == normalize_bindings(fresh_content):
        print("\n✓ Bindings are in sync!")
        print("\nAll FFI bindings match the Rust exports.")
        return 0
    else:
        print("\n✗ Bindings are OUT OF SYNC!")
        print("\nThe generated bindings do not match the current Rust FFI exports.")
        print("\nTo fix, run: just gen-bindings")
        print("\nThen commit the updated bindings file.")
        return 1


def normalize_bindings(content: str) -> str:
    """
    Normalize bindings content for comparison.

    Removes timestamp comments and other non-semantic differences.
    """
    lines = []
    for line in content.split('\n'):
        # Skip timestamp or generation-time specific comments
        if 'generated by' in line.lower() or 'do not edit' in line.lower():
            continue
        lines.append(line)

    return '\n'.join(lines)


if __name__ == '__main__':
    sys.exit(main())
