//! Session recording and replay data structures.
//!
//! This module provides types for recording keyboard event sessions
//! and replaying them deterministically for debugging and testing.

use crate::engine::{EngineState, InputEvent, ModifierState, OutputAction, TimingConfig};
use serde::{Deserialize, Serialize};

/// Version of the session file format.
pub const SESSION_FILE_VERSION: u32 = 1;

/// Type of decision made for an input event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum DecisionType {
    /// Event passed through unchanged.
    #[default]
    PassThrough,
    /// Event was remapped to another key.
    Remap,
    /// Event was blocked.
    Block,
    /// Event triggered a tap action.
    Tap,
    /// Event triggered a hold action.
    Hold,
    /// Event was part of a combo sequence.
    Combo,
    /// Event triggered a layer change.
    Layer,
    /// Event triggered a modifier change.
    Modifier,
}

/// A single recorded event with its processing metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventRecord {
    /// Sequence number (0-indexed).
    pub seq: u64,
    /// Timestamp in microseconds since session start.
    pub timestamp_us: u64,
    /// The input event that was processed.
    pub input: InputEvent,
    /// Output actions generated by the engine.
    pub output: Vec<OutputAction>,
    /// Type of decision made by the engine.
    pub decision_type: DecisionType,
    /// Active layers at the time of the event.
    pub active_layers: Vec<u32>,
    /// Modifier state at the time of the event.
    pub modifiers_state: ModifierState,
    /// Processing latency in microseconds.
    pub latency_us: u64,
}

/// Builder for EventRecord to avoid too-many-arguments.
#[derive(Debug, Default)]
pub struct EventRecordBuilder {
    seq: u64,
    timestamp_us: u64,
    input: Option<InputEvent>,
    output: Vec<OutputAction>,
    decision_type: DecisionType,
    active_layers: Vec<u32>,
    modifiers_state: ModifierState,
    latency_us: u64,
}

impl EventRecordBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set sequence number.
    pub fn seq(mut self, seq: u64) -> Self {
        self.seq = seq;
        self
    }

    /// Set timestamp.
    pub fn timestamp_us(mut self, ts: u64) -> Self {
        self.timestamp_us = ts;
        self
    }

    /// Set input event.
    pub fn input(mut self, input: InputEvent) -> Self {
        self.input = Some(input);
        self
    }

    /// Set output actions.
    pub fn output(mut self, output: Vec<OutputAction>) -> Self {
        self.output = output;
        self
    }

    /// Set decision type.
    pub fn decision_type(mut self, dt: DecisionType) -> Self {
        self.decision_type = dt;
        self
    }

    /// Set active layers.
    pub fn active_layers(mut self, layers: Vec<u32>) -> Self {
        self.active_layers = layers;
        self
    }

    /// Set modifier state.
    pub fn modifiers_state(mut self, mods: ModifierState) -> Self {
        self.modifiers_state = mods;
        self
    }

    /// Set latency.
    pub fn latency_us(mut self, latency: u64) -> Self {
        self.latency_us = latency;
        self
    }

    /// Build the EventRecord.
    pub fn build(self) -> EventRecord {
        EventRecord {
            seq: self.seq,
            timestamp_us: self.timestamp_us,
            input: self.input.unwrap_or_default(),
            output: self.output,
            decision_type: self.decision_type,
            active_layers: self.active_layers,
            modifiers_state: self.modifiers_state,
            latency_us: self.latency_us,
        }
    }
}

impl EventRecord {
    /// Create a builder for EventRecord.
    pub fn builder() -> EventRecordBuilder {
        EventRecordBuilder::new()
    }
}

/// A complete recorded session that can be replayed.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionFile {
    /// File format version for schema evolution.
    pub version: u32,
    /// ISO 8601 timestamp when session was created.
    pub created_at: String,
    /// Path to the script used during recording (if any).
    pub script_path: Option<String>,
    /// Timing configuration used during recording.
    pub timing_config: TimingConfig,
    /// Initial engine state before first event.
    pub initial_state: EngineState,
    /// Recorded events in chronological order.
    pub events: Vec<EventRecord>,
}

impl SessionFile {
    /// Create a new session file.
    pub fn new(
        created_at: String,
        script_path: Option<String>,
        timing_config: TimingConfig,
        initial_state: EngineState,
    ) -> Self {
        Self {
            version: SESSION_FILE_VERSION,
            created_at,
            script_path,
            timing_config,
            initial_state,
            events: Vec::new(),
        }
    }

    /// Add an event to the session.
    pub fn add_event(&mut self, event: EventRecord) {
        self.events.push(event);
    }

    /// Serialize to JSON string.
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    /// Deserialize from JSON string.
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(json)
    }

    /// Total number of recorded events.
    pub fn event_count(&self) -> usize {
        self.events.len()
    }

    /// Total duration of the session in microseconds.
    pub fn duration_us(&self) -> u64 {
        self.events.last().map(|e| e.timestamp_us).unwrap_or(0)
    }

    /// Average processing latency in microseconds.
    pub fn avg_latency_us(&self) -> u64 {
        if self.events.is_empty() {
            return 0;
        }
        let total: u64 = self.events.iter().map(|e| e.latency_us).sum();
        total / self.events.len() as u64
    }
}

/// Infer decision type from output actions.
pub fn infer_decision_type(input: &InputEvent, output: &[OutputAction]) -> DecisionType {
    if output.is_empty() {
        return DecisionType::PassThrough;
    }

    // Check for block
    if output.iter().any(|o| matches!(o, OutputAction::Block)) {
        return DecisionType::Block;
    }

    // Check for pass-through
    if output
        .iter()
        .all(|o| matches!(o, OutputAction::PassThrough))
    {
        return DecisionType::PassThrough;
    }

    // Check for tap pattern (down + up in quick succession) - must check before remap
    if output.len() == 2 {
        if let (OutputAction::KeyDown(k1), OutputAction::KeyUp(k2)) = (&output[0], &output[1]) {
            if k1 == k2 {
                return DecisionType::Tap;
            }
        }
    }

    // Check for remap (single key down/up with different key)
    if let Some(OutputAction::KeyDown(key) | OutputAction::KeyUp(key) | OutputAction::KeyTap(key)) =
        output.first()
    {
        if *key != input.key {
            return DecisionType::Remap;
        }
    }

    DecisionType::PassThrough
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::{KeyCode, LayerStack};

    fn make_initial_state() -> EngineState {
        EngineState {
            pressed_keys: vec![],
            modifiers: ModifierState::default(),
            layers: LayerStack::new(),
            pending: vec![],
            timing: TimingConfig::default(),
            safe_mode: false,
        }
    }

    #[test]
    fn event_record_serializes_correctly() {
        let input = InputEvent::key_down(KeyCode::A, 1000);
        let output = vec![OutputAction::KeyDown(KeyCode::B)];
        let record = EventRecord::builder()
            .seq(0)
            .timestamp_us(1000)
            .input(input)
            .output(output)
            .decision_type(DecisionType::Remap)
            .active_layers(vec![0])
            .modifiers_state(ModifierState::default())
            .latency_us(50)
            .build();

        let json = serde_json::to_string(&record).expect("serialize");
        let decoded: EventRecord = serde_json::from_str(&json).expect("deserialize");

        assert_eq!(decoded.seq, 0);
        assert_eq!(decoded.timestamp_us, 1000);
        assert_eq!(decoded.decision_type, DecisionType::Remap);
        assert_eq!(decoded.active_layers, vec![0]);
        assert_eq!(decoded.latency_us, 50);
    }

    #[test]
    fn session_file_roundtrip() {
        let mut session = SessionFile::new(
            "2024-01-15T10:30:00Z".to_string(),
            Some("/path/to/script.rhai".to_string()),
            TimingConfig::default(),
            make_initial_state(),
        );

        let input = InputEvent::key_down(KeyCode::CapsLock, 5000);
        let output = vec![
            OutputAction::KeyDown(KeyCode::Escape),
            OutputAction::KeyUp(KeyCode::Escape),
        ];
        session.add_event(
            EventRecord::builder()
                .seq(0)
                .timestamp_us(5000)
                .input(input)
                .output(output)
                .decision_type(DecisionType::Tap)
                .active_layers(vec![0])
                .modifiers_state(ModifierState::default())
                .latency_us(100)
                .build(),
        );

        let json = session.to_json().expect("serialize");
        let decoded = SessionFile::from_json(&json).expect("deserialize");

        assert_eq!(decoded.version, SESSION_FILE_VERSION);
        assert_eq!(decoded.created_at, "2024-01-15T10:30:00Z");
        assert_eq!(
            decoded.script_path,
            Some("/path/to/script.rhai".to_string())
        );
        assert_eq!(decoded.event_count(), 1);
    }

    #[test]
    fn session_file_statistics() {
        let mut session = SessionFile::new(
            "2024-01-15T10:30:00Z".to_string(),
            None,
            TimingConfig::default(),
            make_initial_state(),
        );

        // Add events with different timestamps and latencies
        for i in 0..5 {
            let input = InputEvent::key_down(KeyCode::A, i * 10_000);
            session.add_event(
                EventRecord::builder()
                    .seq(i)
                    .timestamp_us(i * 10_000)
                    .input(input)
                    .output(vec![OutputAction::KeyDown(KeyCode::A)])
                    .decision_type(DecisionType::PassThrough)
                    .active_layers(vec![0])
                    .modifiers_state(ModifierState::default())
                    .latency_us((i + 1) * 10) // latencies: 10, 20, 30, 40, 50
                    .build(),
            );
        }

        assert_eq!(session.event_count(), 5);
        assert_eq!(session.duration_us(), 40_000);
        assert_eq!(session.avg_latency_us(), 30); // (10+20+30+40+50)/5 = 30
    }

    #[test]
    fn infer_decision_type_passthrough() {
        let input = InputEvent::key_down(KeyCode::A, 0);
        let output = vec![OutputAction::PassThrough];
        assert_eq!(
            infer_decision_type(&input, &output),
            DecisionType::PassThrough
        );
    }

    #[test]
    fn infer_decision_type_block() {
        let input = InputEvent::key_down(KeyCode::A, 0);
        let output = vec![OutputAction::Block];
        assert_eq!(infer_decision_type(&input, &output), DecisionType::Block);
    }

    #[test]
    fn infer_decision_type_remap() {
        let input = InputEvent::key_down(KeyCode::CapsLock, 0);
        let output = vec![OutputAction::KeyDown(KeyCode::Escape)];
        assert_eq!(infer_decision_type(&input, &output), DecisionType::Remap);
    }

    #[test]
    fn infer_decision_type_tap() {
        let input = InputEvent::key_down(KeyCode::A, 0);
        let output = vec![
            OutputAction::KeyDown(KeyCode::Escape),
            OutputAction::KeyUp(KeyCode::Escape),
        ];
        assert_eq!(infer_decision_type(&input, &output), DecisionType::Tap);
    }

    #[test]
    fn version_for_schema_evolution() {
        let session = SessionFile::new(
            "2024-01-15T10:30:00Z".to_string(),
            None,
            TimingConfig::default(),
            make_initial_state(),
        );
        assert_eq!(session.version, 1);
    }

    #[test]
    fn empty_session_statistics() {
        let session = SessionFile::new(
            "2024-01-15T10:30:00Z".to_string(),
            None,
            TimingConfig::default(),
            make_initial_state(),
        );

        assert_eq!(session.event_count(), 0);
        assert_eq!(session.duration_us(), 0);
        assert_eq!(session.avg_latency_us(), 0);
    }

    #[test]
    fn decision_type_serializes() {
        let types = [
            DecisionType::PassThrough,
            DecisionType::Remap,
            DecisionType::Block,
            DecisionType::Tap,
            DecisionType::Hold,
            DecisionType::Combo,
            DecisionType::Layer,
            DecisionType::Modifier,
        ];

        for dt in types {
            let json = serde_json::to_string(&dt).expect("serialize");
            let decoded: DecisionType = serde_json::from_str(&json).expect("deserialize");
            assert_eq!(decoded, dt);
        }
    }
}
