//! Session recording and replay data structures.
//!
//! This module provides types for recording keyboard event sessions
//! and replaying them deterministically for debugging and testing.

use crate::engine::{EngineState, InputEvent, ModifierState, OutputAction, TimingConfig};
use serde::{Deserialize, Serialize};
use std::fs::File;
use std::io::BufWriter;
use std::path::Path;
use std::time::Instant;

/// Version of the session file format.
pub const SESSION_FILE_VERSION: u32 = 1;

/// Type of decision made for an input event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum DecisionType {
    /// Event passed through unchanged.
    #[default]
    PassThrough,
    /// Event was remapped to another key.
    Remap,
    /// Event was blocked.
    Block,
    /// Event triggered a tap action.
    Tap,
    /// Event triggered a hold action.
    Hold,
    /// Event was part of a combo sequence.
    Combo,
    /// Event triggered a layer change.
    Layer,
    /// Event triggered a modifier change.
    Modifier,
}

/// A single recorded event with its processing metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventRecord {
    /// Sequence number (0-indexed).
    pub seq: u64,
    /// Timestamp in microseconds since session start.
    pub timestamp_us: u64,
    /// The input event that was processed.
    pub input: InputEvent,
    /// Output actions generated by the engine.
    pub output: Vec<OutputAction>,
    /// Type of decision made by the engine.
    pub decision_type: DecisionType,
    /// Active layers at the time of the event.
    pub active_layers: Vec<u32>,
    /// Modifier state at the time of the event.
    pub modifiers_state: ModifierState,
    /// Processing latency in microseconds.
    pub latency_us: u64,
}

/// Builder for EventRecord to avoid too-many-arguments.
#[derive(Debug, Default)]
pub struct EventRecordBuilder {
    seq: u64,
    timestamp_us: u64,
    input: Option<InputEvent>,
    output: Vec<OutputAction>,
    decision_type: DecisionType,
    active_layers: Vec<u32>,
    modifiers_state: ModifierState,
    latency_us: u64,
}

impl EventRecordBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set sequence number.
    pub fn seq(mut self, seq: u64) -> Self {
        self.seq = seq;
        self
    }

    /// Set timestamp.
    pub fn timestamp_us(mut self, ts: u64) -> Self {
        self.timestamp_us = ts;
        self
    }

    /// Set input event.
    pub fn input(mut self, input: InputEvent) -> Self {
        self.input = Some(input);
        self
    }

    /// Set output actions.
    pub fn output(mut self, output: Vec<OutputAction>) -> Self {
        self.output = output;
        self
    }

    /// Set decision type.
    pub fn decision_type(mut self, dt: DecisionType) -> Self {
        self.decision_type = dt;
        self
    }

    /// Set active layers.
    pub fn active_layers(mut self, layers: Vec<u32>) -> Self {
        self.active_layers = layers;
        self
    }

    /// Set modifier state.
    pub fn modifiers_state(mut self, mods: ModifierState) -> Self {
        self.modifiers_state = mods;
        self
    }

    /// Set latency.
    pub fn latency_us(mut self, latency: u64) -> Self {
        self.latency_us = latency;
        self
    }

    /// Build the EventRecord.
    pub fn build(self) -> EventRecord {
        EventRecord {
            seq: self.seq,
            timestamp_us: self.timestamp_us,
            input: self.input.unwrap_or_default(),
            output: self.output,
            decision_type: self.decision_type,
            active_layers: self.active_layers,
            modifiers_state: self.modifiers_state,
            latency_us: self.latency_us,
        }
    }
}

impl EventRecord {
    /// Create a builder for EventRecord.
    pub fn builder() -> EventRecordBuilder {
        EventRecordBuilder::new()
    }
}

/// A complete recorded session that can be replayed.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionFile {
    /// File format version for schema evolution.
    pub version: u32,
    /// ISO 8601 timestamp when session was created.
    pub created_at: String,
    /// Path to the script used during recording (if any).
    pub script_path: Option<String>,
    /// Timing configuration used during recording.
    pub timing_config: TimingConfig,
    /// Initial engine state before first event.
    pub initial_state: EngineState,
    /// Recorded events in chronological order.
    pub events: Vec<EventRecord>,
}

impl SessionFile {
    /// Create a new session file.
    pub fn new(
        created_at: String,
        script_path: Option<String>,
        timing_config: TimingConfig,
        initial_state: EngineState,
    ) -> Self {
        Self {
            version: SESSION_FILE_VERSION,
            created_at,
            script_path,
            timing_config,
            initial_state,
            events: Vec::new(),
        }
    }

    /// Add an event to the session.
    pub fn add_event(&mut self, event: EventRecord) {
        self.events.push(event);
    }

    /// Serialize to JSON string.
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    /// Deserialize from JSON string.
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(json)
    }

    /// Total number of recorded events.
    pub fn event_count(&self) -> usize {
        self.events.len()
    }

    /// Total duration of the session in microseconds.
    pub fn duration_us(&self) -> u64 {
        self.events.last().map(|e| e.timestamp_us).unwrap_or(0)
    }

    /// Average processing latency in microseconds.
    pub fn avg_latency_us(&self) -> u64 {
        if self.events.is_empty() {
            return 0;
        }
        let total: u64 = self.events.iter().map(|e| e.latency_us).sum();
        total / self.events.len() as u64
    }
}

/// Error type for recording operations.
#[derive(Debug)]
pub enum RecordingError {
    /// I/O error during file operations.
    Io(std::io::Error),
    /// Serialization error.
    Serialization(serde_json::Error),
}

impl std::fmt::Display for RecordingError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RecordingError::Io(e) => write!(f, "I/O error: {}", e),
            RecordingError::Serialization(e) => write!(f, "Serialization error: {}", e),
        }
    }
}

impl std::error::Error for RecordingError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            RecordingError::Io(e) => Some(e),
            RecordingError::Serialization(e) => Some(e),
        }
    }
}

impl From<std::io::Error> for RecordingError {
    fn from(e: std::io::Error) -> Self {
        RecordingError::Io(e)
    }
}

impl From<serde_json::Error> for RecordingError {
    fn from(e: serde_json::Error) -> Self {
        RecordingError::Serialization(e)
    }
}

/// Middleware for recording keyboard events to a .krx session file.
///
/// Events are buffered in memory and written to disk when `finish()` is called.
/// This ensures atomic writes and avoids I/O during event processing.
#[derive(Debug)]
pub struct EventRecorder {
    /// Path to the output .krx file.
    path: std::path::PathBuf,
    /// Instant when recording started.
    session_start: Instant,
    /// Buffered events.
    events: Vec<EventRecord>,
    /// Script path used during recording.
    script_path: Option<String>,
    /// Timing configuration.
    timing_config: TimingConfig,
    /// Initial engine state.
    initial_state: EngineState,
}

impl EventRecorder {
    /// Create a new EventRecorder that will write to the given path.
    ///
    /// The file is not created until `finish()` is called.
    pub fn new<P: AsRef<Path>>(
        path: P,
        script_path: Option<String>,
        timing_config: TimingConfig,
        initial_state: EngineState,
    ) -> Result<Self, RecordingError> {
        let path = path.as_ref().to_path_buf();

        // Verify parent directory exists (fail fast)
        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() && !parent.exists() {
                return Err(RecordingError::Io(std::io::Error::new(
                    std::io::ErrorKind::NotFound,
                    format!("Parent directory does not exist: {}", parent.display()),
                )));
            }
        }

        Ok(Self {
            path,
            session_start: Instant::now(),
            events: Vec::new(),
            script_path,
            timing_config,
            initial_state,
        })
    }

    /// Record an event.
    ///
    /// Events are buffered in memory until `finish()` is called.
    pub fn record_event(&mut self, event: EventRecord) {
        self.events.push(event);
    }

    /// Get the number of recorded events.
    pub fn event_count(&self) -> usize {
        self.events.len()
    }

    /// Get elapsed time since recording started in microseconds.
    pub fn elapsed_us(&self) -> u64 {
        self.session_start.elapsed().as_micros() as u64
    }

    /// Finish recording and write the session file.
    ///
    /// Consumes the recorder and writes all buffered events to the .krx file.
    pub fn finish(self) -> Result<SessionFile, RecordingError> {
        let created_at = chrono::Utc::now().to_rfc3339();

        let session = SessionFile {
            version: SESSION_FILE_VERSION,
            created_at,
            script_path: self.script_path,
            timing_config: self.timing_config,
            initial_state: self.initial_state,
            events: self.events,
        };

        // Write to file
        let file = File::create(&self.path)?;
        let writer = BufWriter::new(file);
        serde_json::to_writer_pretty(writer, &session)?;

        Ok(session)
    }

    /// Abort recording without writing.
    ///
    /// Useful for graceful cleanup on error.
    pub fn abort(self) {
        // Just drop without writing
    }
}

/// Infer decision type from output actions.
pub fn infer_decision_type(input: &InputEvent, output: &[OutputAction]) -> DecisionType {
    if output.is_empty() {
        return DecisionType::PassThrough;
    }

    // Check for block
    if output.iter().any(|o| matches!(o, OutputAction::Block)) {
        return DecisionType::Block;
    }

    // Check for pass-through
    if output
        .iter()
        .all(|o| matches!(o, OutputAction::PassThrough))
    {
        return DecisionType::PassThrough;
    }

    // Check for tap pattern (down + up in quick succession) - must check before remap
    if output.len() == 2 {
        if let (OutputAction::KeyDown(k1), OutputAction::KeyUp(k2)) = (&output[0], &output[1]) {
            if k1 == k2 {
                return DecisionType::Tap;
            }
        }
    }

    // Check for remap (single key down/up with different key)
    if let Some(OutputAction::KeyDown(key) | OutputAction::KeyUp(key) | OutputAction::KeyTap(key)) =
        output.first()
    {
        if *key != input.key {
            return DecisionType::Remap;
        }
    }

    DecisionType::PassThrough
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::{KeyCode, LayerStack};

    fn make_initial_state() -> EngineState {
        EngineState {
            pressed_keys: vec![],
            modifiers: ModifierState::default(),
            layers: LayerStack::new(),
            pending: vec![],
            timing: TimingConfig::default(),
            safe_mode: false,
        }
    }

    #[test]
    fn event_record_serializes_correctly() {
        let input = InputEvent::key_down(KeyCode::A, 1000);
        let output = vec![OutputAction::KeyDown(KeyCode::B)];
        let record = EventRecord::builder()
            .seq(0)
            .timestamp_us(1000)
            .input(input)
            .output(output)
            .decision_type(DecisionType::Remap)
            .active_layers(vec![0])
            .modifiers_state(ModifierState::default())
            .latency_us(50)
            .build();

        let json = serde_json::to_string(&record).expect("serialize");
        let decoded: EventRecord = serde_json::from_str(&json).expect("deserialize");

        assert_eq!(decoded.seq, 0);
        assert_eq!(decoded.timestamp_us, 1000);
        assert_eq!(decoded.decision_type, DecisionType::Remap);
        assert_eq!(decoded.active_layers, vec![0]);
        assert_eq!(decoded.latency_us, 50);
    }

    #[test]
    fn session_file_roundtrip() {
        let mut session = SessionFile::new(
            "2024-01-15T10:30:00Z".to_string(),
            Some("/path/to/script.rhai".to_string()),
            TimingConfig::default(),
            make_initial_state(),
        );

        let input = InputEvent::key_down(KeyCode::CapsLock, 5000);
        let output = vec![
            OutputAction::KeyDown(KeyCode::Escape),
            OutputAction::KeyUp(KeyCode::Escape),
        ];
        session.add_event(
            EventRecord::builder()
                .seq(0)
                .timestamp_us(5000)
                .input(input)
                .output(output)
                .decision_type(DecisionType::Tap)
                .active_layers(vec![0])
                .modifiers_state(ModifierState::default())
                .latency_us(100)
                .build(),
        );

        let json = session.to_json().expect("serialize");
        let decoded = SessionFile::from_json(&json).expect("deserialize");

        assert_eq!(decoded.version, SESSION_FILE_VERSION);
        assert_eq!(decoded.created_at, "2024-01-15T10:30:00Z");
        assert_eq!(
            decoded.script_path,
            Some("/path/to/script.rhai".to_string())
        );
        assert_eq!(decoded.event_count(), 1);
    }

    #[test]
    fn session_file_statistics() {
        let mut session = SessionFile::new(
            "2024-01-15T10:30:00Z".to_string(),
            None,
            TimingConfig::default(),
            make_initial_state(),
        );

        // Add events with different timestamps and latencies
        for i in 0..5 {
            let input = InputEvent::key_down(KeyCode::A, i * 10_000);
            session.add_event(
                EventRecord::builder()
                    .seq(i)
                    .timestamp_us(i * 10_000)
                    .input(input)
                    .output(vec![OutputAction::KeyDown(KeyCode::A)])
                    .decision_type(DecisionType::PassThrough)
                    .active_layers(vec![0])
                    .modifiers_state(ModifierState::default())
                    .latency_us((i + 1) * 10) // latencies: 10, 20, 30, 40, 50
                    .build(),
            );
        }

        assert_eq!(session.event_count(), 5);
        assert_eq!(session.duration_us(), 40_000);
        assert_eq!(session.avg_latency_us(), 30); // (10+20+30+40+50)/5 = 30
    }

    #[test]
    fn infer_decision_type_passthrough() {
        let input = InputEvent::key_down(KeyCode::A, 0);
        let output = vec![OutputAction::PassThrough];
        assert_eq!(
            infer_decision_type(&input, &output),
            DecisionType::PassThrough
        );
    }

    #[test]
    fn infer_decision_type_block() {
        let input = InputEvent::key_down(KeyCode::A, 0);
        let output = vec![OutputAction::Block];
        assert_eq!(infer_decision_type(&input, &output), DecisionType::Block);
    }

    #[test]
    fn infer_decision_type_remap() {
        let input = InputEvent::key_down(KeyCode::CapsLock, 0);
        let output = vec![OutputAction::KeyDown(KeyCode::Escape)];
        assert_eq!(infer_decision_type(&input, &output), DecisionType::Remap);
    }

    #[test]
    fn infer_decision_type_tap() {
        let input = InputEvent::key_down(KeyCode::A, 0);
        let output = vec![
            OutputAction::KeyDown(KeyCode::Escape),
            OutputAction::KeyUp(KeyCode::Escape),
        ];
        assert_eq!(infer_decision_type(&input, &output), DecisionType::Tap);
    }

    #[test]
    fn version_for_schema_evolution() {
        let session = SessionFile::new(
            "2024-01-15T10:30:00Z".to_string(),
            None,
            TimingConfig::default(),
            make_initial_state(),
        );
        assert_eq!(session.version, 1);
    }

    #[test]
    fn empty_session_statistics() {
        let session = SessionFile::new(
            "2024-01-15T10:30:00Z".to_string(),
            None,
            TimingConfig::default(),
            make_initial_state(),
        );

        assert_eq!(session.event_count(), 0);
        assert_eq!(session.duration_us(), 0);
        assert_eq!(session.avg_latency_us(), 0);
    }

    #[test]
    fn decision_type_serializes() {
        let types = [
            DecisionType::PassThrough,
            DecisionType::Remap,
            DecisionType::Block,
            DecisionType::Tap,
            DecisionType::Hold,
            DecisionType::Combo,
            DecisionType::Layer,
            DecisionType::Modifier,
        ];

        for dt in types {
            let json = serde_json::to_string(&dt).expect("serialize");
            let decoded: DecisionType = serde_json::from_str(&json).expect("deserialize");
            assert_eq!(decoded, dt);
        }
    }

    #[test]
    fn event_recorder_records_events() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let path = dir.path().join("test_session.krx");

        let mut recorder = EventRecorder::new(
            &path,
            Some("/scripts/test.rhai".to_string()),
            TimingConfig::default(),
            make_initial_state(),
        )
        .expect("create recorder");

        assert_eq!(recorder.event_count(), 0);

        // Record some events
        let input = InputEvent::key_down(KeyCode::A, 1000);
        recorder.record_event(
            EventRecord::builder()
                .seq(0)
                .timestamp_us(1000)
                .input(input)
                .output(vec![OutputAction::KeyDown(KeyCode::B)])
                .decision_type(DecisionType::Remap)
                .active_layers(vec![0])
                .modifiers_state(ModifierState::default())
                .latency_us(50)
                .build(),
        );

        assert_eq!(recorder.event_count(), 1);

        let input2 = InputEvent::key_up(KeyCode::A, 2000);
        recorder.record_event(
            EventRecord::builder()
                .seq(1)
                .timestamp_us(2000)
                .input(input2)
                .output(vec![OutputAction::KeyUp(KeyCode::B)])
                .decision_type(DecisionType::Remap)
                .active_layers(vec![0])
                .modifiers_state(ModifierState::default())
                .latency_us(45)
                .build(),
        );

        assert_eq!(recorder.event_count(), 2);

        // Finish recording
        let session = recorder.finish().expect("finish recording");

        // Verify session
        assert_eq!(session.version, SESSION_FILE_VERSION);
        assert_eq!(session.script_path, Some("/scripts/test.rhai".to_string()));
        assert_eq!(session.event_count(), 2);
        assert_eq!(session.events[0].seq, 0);
        assert_eq!(session.events[1].seq, 1);

        // Verify file was written
        assert!(path.exists());

        // Verify file content can be read back
        let content = std::fs::read_to_string(&path).expect("read file");
        let loaded = SessionFile::from_json(&content).expect("parse file");
        assert_eq!(loaded.event_count(), 2);
    }

    #[test]
    fn event_recorder_fails_on_nonexistent_parent() {
        let result = EventRecorder::new(
            "/nonexistent/directory/session.krx",
            None,
            TimingConfig::default(),
            make_initial_state(),
        );

        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(matches!(err, RecordingError::Io(_)));
    }

    #[test]
    fn event_recorder_abort_does_not_write() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let path = dir.path().join("aborted_session.krx");

        let mut recorder =
            EventRecorder::new(&path, None, TimingConfig::default(), make_initial_state())
                .expect("create recorder");

        // Record an event
        let input = InputEvent::key_down(KeyCode::A, 1000);
        recorder.record_event(
            EventRecord::builder()
                .seq(0)
                .timestamp_us(1000)
                .input(input)
                .output(vec![OutputAction::PassThrough])
                .decision_type(DecisionType::PassThrough)
                .active_layers(vec![0])
                .modifiers_state(ModifierState::default())
                .latency_us(10)
                .build(),
        );

        // Abort instead of finish
        recorder.abort();

        // File should not exist
        assert!(!path.exists());
    }

    #[test]
    fn event_recorder_elapsed_time() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let path = dir.path().join("elapsed_session.krx");

        let recorder =
            EventRecorder::new(&path, None, TimingConfig::default(), make_initial_state())
                .expect("create recorder");

        // Sleep a tiny bit and check elapsed
        std::thread::sleep(std::time::Duration::from_millis(1));
        let elapsed = recorder.elapsed_us();

        // Should be at least 1000 microseconds (1ms)
        assert!(
            elapsed >= 1000,
            "elapsed should be at least 1ms, got {}",
            elapsed
        );

        recorder.abort();
    }

    #[test]
    fn recording_error_display() {
        let io_err = RecordingError::Io(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            "test error",
        ));
        let display = format!("{}", io_err);
        assert!(display.contains("I/O error"));
        assert!(display.contains("test error"));
    }
}
