/*
 Generated by typeshare 1.13.4
*/

/** Result of profile activation. */
export interface ActivationResult {
	compileTimeMs: number;
	reloadTimeMs: number;
	success: boolean;
	error?: string;
}

/** Activation result returned by activate_profile */
export interface ActivationRpcResult {
	success: boolean;
	compileTimeMs: number;
	reloadTimeMs: number;
	error?: string;
}

/** Current daemon state snapshot. */
export interface DaemonState {
	/** Active modifier IDs (e.g., ["MD_00", "MD_01"]). */
	modifiers: string[];
	/** Active lock IDs (e.g., ["LK_00"]). */
	locks: string[];
	/** Current active layer name. */
	layer: string;
	/** Currently active profile name (if any). */
	activeProfile?: string;
}

/** Device metadata entry */
export interface DeviceEntry {
	/** Unique device identifier (max 256 chars) */
	id: string;
	/** User-friendly name (max 64 chars) */
	name: string;
	/** Serial number if available */
	serial?: string;
	/** Associated layout name (max 32 chars) */
	layout?: string;
	/** Last seen timestamp (Unix seconds) */
	lastSeen: number;
}

/** Device information returned by RPC methods */
export interface DeviceRpcInfo {
	id: string;
	name: string;
	path: string;
	serial?: string;
	active: boolean;
	layout?: string;
	isVirtual: boolean;
	enabled: boolean;
	scope?: string;
}

/** Error notification data (WS-005). */
export interface ErrorData {
	/** Error code (e.g., "CONFIG_LOAD_FAILED", "PROFILE_NOT_FOUND"). */
	code: string;
	/** Human-readable error message. */
	message: string;
	/** Additional context (e.g., file path, profile name). */
	context?: string;
	/** Timestamp in microseconds since UNIX epoch. */
	timestamp: number;
}

/** Event in event log */
export interface EventRpcEntry {
	timestamp: number;
	keyCode: number;
	eventType: string;
	deviceId: string;
}

/** Individual key event data. */
export interface KeyEventData {
	/** Timestamp in microseconds since UNIX epoch. */
	timestamp: number;
	/** Key code (e.g., "KEY_A"). */
	keyCode: string;
	/** Event type ("press" or "release"). */
	eventType: string;
	/** Input key (before mapping). */
	input: string;
	/** Output key (after mapping). */
	output: string;
	/** Processing latency in microseconds. */
	latency: number;
	/** Device ID (unique identifier for the source device). */
	deviceId?: string;
	/** Device name (human-readable name). */
	deviceName?: string;
	/** Mapping type applied (e.g., "simple", "tap_hold", "layer_switch"). */
	mappingType?: string;
	/** Whether a mapping was triggered for this event. */
	mappingTriggered: boolean;
}

/** Latency statistics returned by get_latency */
export interface LatencyRpcStats {
	minUs: number;
	avgUs: number;
	maxUs: number;
	p50Us: number;
	p95Us: number;
	p99Us: number;
	count: number;
}

/** Latency statistics. */
export interface LatencyStats {
	/** Minimum latency in microseconds. */
	min: number;
	/** Average latency in microseconds. */
	avg: number;
	/** Maximum latency in microseconds. */
	max: number;
	/** 95th percentile latency in microseconds. */
	p95: number;
	/** 99th percentile latency in microseconds. */
	p99: number;
	/** Timestamp of this stats snapshot (microseconds since UNIX epoch). */
	timestamp: number;
}

/** Profile configuration returned by get_profile_config */
export interface ProfileConfigRpc {
	name: string;
	source: string;
}

/** Metadata for a single profile. */
export interface ProfileMetadata {
	name: string;
	layerCount: number;
	activatedBy?: string;
}

/** Profile information returned by RPC methods */
export interface ProfileRpcInfo {
	name: string;
	layerCount: number;
	active: boolean;
	modifiedAtSecs: number;
}

/** Result of restart_daemon command */
export interface RestartResult {
	success: boolean;
	message: string;
}

/** RPC error structure following JSON-RPC 2.0 conventions */
export interface RpcError {
	/** Numeric error code */
	code: number;
	/** Human-readable error message */
	message: string;
	/** Optional additional error data */
	data: any;
}

/** Messages sent from client to server */
export type ClientMessage = 
	/** Query request - read-only operation that returns data */
	| { type: "query", content: {
	/** Unique identifier for request/response correlation */
	id: string;
	/** Method name to invoke */
	method: string;
	/** Optional parameters for the method */
	params?: any;
}}
	/** Command request - operation that modifies state */
	| { type: "command", content: {
	/** Unique identifier for request/response correlation */
	id: string;
	/** Method name to invoke */
	method: string;
	/** Optional parameters for the method */
	params?: any;
}}
	/** Subscribe to a channel for real-time updates */
	| { type: "subscribe", content: {
	/** Unique identifier for request/response correlation */
	id: string;
	/** Channel name to subscribe to */
	channel: string;
}}
	/** Unsubscribe from a channel */
	| { type: "unsubscribe", content: {
	/** Unique identifier for request/response correlation */
	id: string;
	/** Channel name to unsubscribe from */
	channel: string;
}};

/** Template for creating new profiles. */
export enum ProfileTemplate {
	/** Empty configuration with minimal valid syntax */
	Blank = "blank",
	/** Simple A→B key remapping example */
	SimpleRemap = "simple_remap",
	/** CapsLock→Escape mapping */
	CapslockEscape = "capslock_escape",
	/** Vim navigation with HJKL layer */
	VimNavigation = "vim_navigation",
	/** Gaming-optimized profile */
	Gaming = "gaming",
}

/** Messages sent from server to client */
export type ServerMessage = 
	/** Response to a query or command */
	| { type: "response", content: {
	/** Request ID this response corresponds to */
	id: string;
	/** Result data (success) or None if error */
	result: any;
	/** Error information (failure) or None if success */
	error?: RpcError;
}}
	/** Event broadcast to subscribed clients */
	| { type: "event", content: {
	/** Channel this event was published on */
	channel: string;
	/** Event data */
	data: any;
}}
	/** Initial handshake message sent on connection */
	| { type: "connected", content: {
	/** Protocol version */
	version: string;
	/** Server timestamp in microseconds */
	timestamp: number;
}};

