/// Service for accessing Rhai API documentation.
///
/// Provides a Flutter-friendly API to load, search, and browse the
/// API documentation for Rhai scripting. Documentation is loaded from
/// JSON files generated by the `keyrx docs generate --format json` command.
library;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

/// Documentation for a single function parameter.
class ParameterDoc {
  const ParameterDoc({
    required this.name,
    required this.typeName,
    required this.description,
    required this.optional,
    this.defaultValue,
  });

  factory ParameterDoc.fromJson(Map<String, dynamic> json) {
    return ParameterDoc(
      name: json['name'] as String,
      typeName: json['type'] as String,
      description: json['description'] as String,
      optional: json['optional'] as bool,
      defaultValue: json['default'] as String?,
    );
  }

  final String name;
  final String typeName;
  final String description;
  final bool optional;
  final String? defaultValue;

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'type': typeName,
      'description': description,
      'optional': optional,
      if (defaultValue != null) 'default': defaultValue,
    };
  }
}

/// Documentation for a function return type.
class ReturnTypeDoc {
  const ReturnTypeDoc({required this.typeName, required this.description});

  factory ReturnTypeDoc.fromJson(Map<String, dynamic> json) {
    return ReturnTypeDoc(
      typeName: json['type'] as String,
      description: json['description'] as String,
    );
  }

  final String typeName;
  final String description;

  Map<String, dynamic> toJson() {
    return {'type': typeName, 'description': description};
  }
}

/// Documentation for a function.
class FunctionDoc {
  const FunctionDoc({
    required this.name,
    required this.description,
    required this.parameters,
    this.returns,
    this.examples = const [],
    this.deprecated,
    this.since,
    this.notes,
    this.snippet = '',
  });

  factory FunctionDoc.fromJson(Map<String, dynamic> json) {
    return FunctionDoc(
      name: json['name'] as String,
      description: json['description'] as String,
      parameters:
          (json['parameters'] as List<dynamic>?)
              ?.map((e) => ParameterDoc.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      returns: json['returns'] != null
          ? ReturnTypeDoc.fromJson(json['returns'] as Map<String, dynamic>)
          : null,
      examples:
          (json['examples'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          [],
      deprecated: json['deprecated'] as String?,
      since: json['since'] as String?,
      notes: json['notes'] as String?,
      snippet: json['snippet'] as String? ?? '',
    );
  }

  final String name;
  final String description;
  final List<ParameterDoc> parameters;
  final ReturnTypeDoc? returns;
  final List<String> examples;
  final String? deprecated;
  final String? since;
  final String? notes;
  final String snippet;

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'description': description,
      'parameters': parameters.map((e) => e.toJson()).toList(),
      if (returns != null) 'returns': returns!.toJson(),
      'examples': examples,
      if (deprecated != null) 'deprecated': deprecated,
      if (since != null) 'since': since,
      if (notes != null) 'notes': notes,
      'snippet': snippet,
    };
  }
}

/// Documentation for a type property.
class PropertyDoc {
  const PropertyDoc({
    required this.name,
    required this.typeName,
    required this.description,
    required this.readonly,
  });

  factory PropertyDoc.fromJson(Map<String, dynamic> json) {
    return PropertyDoc(
      name: json['name'] as String,
      typeName: json['type'] as String,
      description: json['description'] as String,
      readonly: json['readonly'] as bool,
    );
  }

  final String name;
  final String typeName;
  final String description;
  final bool readonly;

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'type': typeName,
      'description': description,
      'readonly': readonly,
    };
  }
}

/// Documentation for a type.
class TypeDoc {
  const TypeDoc({
    required this.name,
    required this.description,
    required this.properties,
    required this.methods,
    this.constructors = const [],
    this.examples = const [],
    this.since,
  });

  factory TypeDoc.fromJson(Map<String, dynamic> json) {
    return TypeDoc(
      name: json['name'] as String,
      description: json['description'] as String,
      properties:
          (json['properties'] as List<dynamic>?)
              ?.map((e) => PropertyDoc.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      methods:
          (json['methods'] as List<dynamic>?)
              ?.map((e) => FunctionDoc.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      constructors:
          (json['constructors'] as List<dynamic>?)
              ?.map((e) => FunctionDoc.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      examples:
          (json['examples'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          [],
      since: json['since'] as String?,
    );
  }

  final String name;
  final String description;
  final List<PropertyDoc> properties;
  final List<FunctionDoc> methods;
  final List<FunctionDoc> constructors;
  final List<String> examples;
  final String? since;

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'description': description,
      'properties': properties.map((e) => e.toJson()).toList(),
      'methods': methods.map((e) => e.toJson()).toList(),
      'constructors': constructors.map((e) => e.toJson()).toList(),
      'examples': examples,
      if (since != null) 'since': since,
    };
  }
}

/// Documentation for a module.
class ModuleDoc {
  const ModuleDoc({
    required this.name,
    this.description,
    required this.functions,
    required this.types,
  });

  factory ModuleDoc.fromJson(String name, Map<String, dynamic> json) {
    return ModuleDoc(
      name: json['name'] as String? ?? name,
      description: json['description'] as String?,
      functions:
          (json['functions'] as List<dynamic>?)
              ?.map((e) => FunctionDoc.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      types:
          (json['types'] as List<dynamic>?)
              ?.map((e) => TypeDoc.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
    );
  }

  final String name;
  final String? description;
  final List<FunctionDoc> functions;
  final List<TypeDoc> types;

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      if (description != null) 'description': description,
      'functions': functions.map((e) => e.toJson()).toList(),
      'types': types.map((e) => e.toJson()).toList(),
    };
  }
}

/// Autocomplete completion item.
class CompletionItem {
  const CompletionItem({
    required this.label,
    required this.kind,
    required this.detail,
    required this.documentation,
    required this.insertText,
    required this.insertTextFormat,
  });

  factory CompletionItem.fromJson(Map<String, dynamic> json) {
    return CompletionItem(
      label: json['label'] as String,
      kind: json['kind'] as String,
      detail: json['detail'] as String,
      documentation: json['documentation'] as String,
      insertText: json['insert_text'] as String,
      insertTextFormat: json['insert_text_format'] as String,
    );
  }

  final String label;
  final String kind;
  final String detail;
  final String documentation;
  final String insertText;
  final String insertTextFormat;

  Map<String, dynamic> toJson() {
    return {
      'label': label,
      'kind': kind,
      'detail': detail,
      'documentation': documentation,
      'insert_text': insertText,
      'insert_text_format': insertTextFormat,
    };
  }
}

/// Search result item.
class SearchResult {
  const SearchResult({
    required this.type,
    required this.module,
    required this.name,
    required this.description,
    required this.relevance,
  });

  /// Type of result (function, type, property, method).
  final String type;

  /// Module name.
  final String module;

  /// Item name.
  final String name;

  /// Item description.
  final String description;

  /// Relevance score (0.0 to 1.0).
  final double relevance;
}

/// Abstraction for API documentation operations.
abstract class ApiDocsService {
  /// Whether documentation has been loaded.
  bool get isLoaded;

  /// List of all module names.
  List<String> get moduleNames;

  /// Load documentation from a JSON file.
  Future<void> loadFromFile(String filePath);

  /// Load documentation from a JSON string.
  Future<void> loadFromJson(String json);

  /// Get documentation for a specific module.
  ModuleDoc? getModule(String name);

  /// Get all modules.
  List<ModuleDoc> getAllModules();

  /// Search for functions and types by query.
  List<SearchResult> search(String query, {int limit = 20});

  /// Get function documentation by name.
  FunctionDoc? getFunction(String moduleName, String functionName);

  /// Get type documentation by name.
  TypeDoc? getType(String moduleName, String typeName);

  /// Get autocomplete items for a given prefix.
  List<CompletionItem> getCompletions(String prefix, {int limit = 10});

  /// Clear all loaded documentation.
  void clear();
}

/// Real ApiDocsService implementation.
class ApiDocsServiceImpl implements ApiDocsService {
  final Map<String, ModuleDoc> _modules = {};
  final List<CompletionItem> _completionItems = [];
  bool _isLoaded = false;

  @override
  bool get isLoaded => _isLoaded;

  @override
  List<String> get moduleNames => _modules.keys.toList()..sort();

  @override
  Future<void> loadFromFile(String filePath) async {
    final file = File(filePath);
    if (!await file.exists()) {
      throw Exception('API docs file not found: $filePath');
    }

    final content = await file.readAsString();
    await loadFromJson(content);
  }

  @override
  Future<void> loadFromJson(String json) async {
    try {
      final data = jsonDecode(json) as Map<String, dynamic>;

      // Load modules
      final modules = data['modules'] as Map<String, dynamic>?;
      if (modules != null) {
        for (final entry in modules.entries) {
          final module = ModuleDoc.fromJson(
            entry.key,
            entry.value as Map<String, dynamic>,
          );
          _modules[module.name] = module;
        }
      }

      // Load autocomplete items
      final autocomplete = data['autocomplete'] as Map<String, dynamic>?;
      if (autocomplete != null) {
        final functions = autocomplete['functions'] as List<dynamic>?;
        if (functions != null) {
          for (final func in functions) {
            _completionItems.add(
              CompletionItem.fromJson(func as Map<String, dynamic>),
            );
          }
        }

        final types = autocomplete['types'] as List<dynamic>?;
        if (types != null) {
          for (final type in types) {
            _completionItems.add(
              CompletionItem.fromJson(type as Map<String, dynamic>),
            );
          }
        }
      }

      _isLoaded = true;
    } catch (e) {
      throw Exception('Failed to parse API docs JSON: $e');
    }
  }

  @override
  ModuleDoc? getModule(String name) {
    return _modules[name];
  }

  @override
  List<ModuleDoc> getAllModules() {
    return _modules.values.toList();
  }

  @override
  List<SearchResult> search(String query, {int limit = 20}) {
    if (query.isEmpty) {
      return [];
    }

    final results = <SearchResult>[];
    final lowerQuery = query.toLowerCase();

    // Search through all modules
    for (final module in _modules.values) {
      // Search functions
      for (final func in module.functions) {
        final score = _calculateRelevance(
          lowerQuery,
          func.name,
          func.description,
        );
        if (score > 0) {
          results.add(
            SearchResult(
              type: 'function',
              module: module.name,
              name: func.name,
              description: func.description,
              relevance: score,
            ),
          );
        }
      }

      // Search types
      for (final type in module.types) {
        final score = _calculateRelevance(
          lowerQuery,
          type.name,
          type.description,
        );
        if (score > 0) {
          results.add(
            SearchResult(
              type: 'type',
              module: module.name,
              name: type.name,
              description: type.description,
              relevance: score,
            ),
          );
        }

        // Search type methods
        for (final method in type.methods) {
          final score = _calculateRelevance(
            lowerQuery,
            method.name,
            method.description,
          );
          if (score > 0) {
            results.add(
              SearchResult(
                type: 'method',
                module: module.name,
                name: '${type.name}.${method.name}',
                description: method.description,
                relevance: score * 0.9, // Slightly lower relevance for methods
              ),
            );
          }
        }

        // Search type properties
        for (final prop in type.properties) {
          final score = _calculateRelevance(
            lowerQuery,
            prop.name,
            prop.description,
          );
          if (score > 0) {
            results.add(
              SearchResult(
                type: 'property',
                module: module.name,
                name: '${type.name}.${prop.name}',
                description: prop.description,
                relevance: score * 0.8, // Even lower relevance for properties
              ),
            );
          }
        }
      }
    }

    // Sort by relevance (highest first) and limit results
    results.sort((a, b) => b.relevance.compareTo(a.relevance));
    return results.take(limit).toList();
  }

  @override
  FunctionDoc? getFunction(String moduleName, String functionName) {
    final module = _modules[moduleName];
    if (module == null) {
      return null;
    }

    return module.functions.cast<FunctionDoc?>().firstWhere(
      (f) => f!.name == functionName,
      orElse: () => null,
    );
  }

  @override
  TypeDoc? getType(String moduleName, String typeName) {
    final module = _modules[moduleName];
    if (module == null) {
      return null;
    }

    return module.types.cast<TypeDoc?>().firstWhere(
      (t) => t!.name == typeName,
      orElse: () => null,
    );
  }

  @override
  List<CompletionItem> getCompletions(String prefix, {int limit = 10}) {
    if (prefix.isEmpty) {
      return _completionItems.take(limit).toList();
    }

    final lowerPrefix = prefix.toLowerCase();
    return _completionItems
        .where((item) => item.label.toLowerCase().startsWith(lowerPrefix))
        .take(limit)
        .toList();
  }

  @override
  void clear() {
    _modules.clear();
    _completionItems.clear();
    _isLoaded = false;
  }

  /// Calculate relevance score for a search query.
  double _calculateRelevance(String query, String name, String description) {
    final lowerName = name.toLowerCase();
    final lowerDesc = description.toLowerCase();

    // Exact match in name gets highest score
    if (lowerName == query) {
      return 1.0;
    }

    // Name starts with query gets high score
    if (lowerName.startsWith(query)) {
      return 0.9;
    }

    // Name contains query gets medium score
    if (lowerName.contains(query)) {
      return 0.7;
    }

    // Description starts with query gets medium-low score
    if (lowerDesc.startsWith(query)) {
      return 0.5;
    }

    // Description contains query gets low score
    if (lowerDesc.contains(query)) {
      return 0.3;
    }

    return 0.0;
  }
}
