/// Utility for building Rhai scripts from mappings and combos.
library;

import '../models/key_mapping.dart';

/// Utility for building Rhai scripts from mappings and combos.
class ScriptGenerator {
  static String build({
    required Iterable<KeyMapping> mappings,
    required Iterable<ComboMapping> combos,
  }) {
    final buffer = StringBuffer()
      ..writeln('// Auto-generated by KeyRx Editor')
      ..writeln('// Edit carefully or re-generate from the UI.')
      ..writeln()
      ..writeln('fn configure() {');

    for (final mapping in mappings) {
      switch (mapping.type) {
        case KeyActionType.remap:
          buffer.writeln(
            '    remap("${mapping.from}", "${mapping.to ?? mapping.from}");',
          );
          break;
        case KeyActionType.block:
          buffer.writeln('    block("${mapping.from}");');
          break;
        case KeyActionType.pass:
          buffer.writeln('    pass("${mapping.from}");');
          break;
      }

      if (mapping.layer != null && mapping.layer!.isNotEmpty) {
        buffer.writeln(
          '    layer("${mapping.layer}", "${mapping.from}", "${mapping.to ?? mapping.from}");',
        );
      }

      if (mapping.tapHoldTap != null &&
          mapping.tapHoldHold != null &&
          mapping.tapHoldTap!.isNotEmpty &&
          mapping.tapHoldHold!.isNotEmpty) {
        buffer.writeln(
          '    tap_hold("${mapping.from}", tap: "${mapping.tapHoldTap}", hold: "${mapping.tapHoldHold}");',
        );
      }
    }

    if (combos.isNotEmpty) {
      buffer.writeln();
      buffer.writeln('    // Combos');
      for (final combo in combos) {
        final keys = combo.keys.map((k) => '"$k"').join(', ');
        buffer.writeln('    combo([$keys], "${combo.output}");');
      }
    }

    buffer.writeln('}');
    return buffer.toString();
  }
}
